// Generated by src/store/__tests__/convertExamples.test.ts from the Convert page's Soft circle
// (glslToGraph, then optimizeGraph as the page runs it). Don't edit by hand:
//   UPDATE_CONVERT_EXAMPLES=1 npx vitest run convertExamples
import type { GraphNode } from '../types/nodeGraph';

export const SOFT_CIRCLE_AS_WRITTEN: GraphNode[] = [
  {
    "id": "fragCoord_1",
    "type": "fragCoord",
    "position": {
      "x": 40,
      "y": 60
    },
    "inputs": {},
    "outputs": {
      "coord": {
        "type": "vec2",
        "label": "Coord"
      }
    },
    "params": {}
  },
  {
    "id": "resolution_2",
    "type": "resolution",
    "position": {
      "x": 40,
      "y": 210
    },
    "inputs": {},
    "outputs": {
      "res": {
        "type": "vec2",
        "label": "Resolution"
      },
      "width": {
        "type": "float",
        "label": "Width"
      },
      "height": {
        "type": "float",
        "label": "Height"
      }
    },
    "params": {}
  },
  {
    "id": "divide_3",
    "type": "divide",
    "position": {
      "x": 480,
      "y": 60
    },
    "inputs": {
      "a": {
        "type": "vec2",
        "label": "A",
        "connection": {
          "nodeId": "fragCoord_1",
          "outputKey": "coord"
        }
      },
      "b": {
        "type": "vec2",
        "label": "B",
        "connection": {
          "nodeId": "resolution_2",
          "outputKey": "res"
        }
      }
    },
    "outputs": {
      "result": {
        "type": "vec2",
        "label": "Result"
      }
    },
    "params": {
      "b": 1,
      "exact": true,
      "outputType": "vec2"
    }
  },
  {
    "id": "subtract_4",
    "type": "subtract",
    "position": {
      "x": 920,
      "y": 60
    },
    "inputs": {
      "a": {
        "type": "vec2",
        "label": "A",
        "connection": {
          "nodeId": "divide_3",
          "outputKey": "result"
        }
      },
      "b": {
        "type": "vec2",
        "label": "B"
      }
    },
    "outputs": {
      "result": {
        "type": "vec2",
        "label": "Result"
      }
    },
    "params": {
      "b": 0.5,
      "outputType": "vec2"
    }
  },
  {
    "id": "length_5",
    "type": "length",
    "position": {
      "x": 1360,
      "y": 60
    },
    "inputs": {
      "input": {
        "type": "vec2",
        "label": "Input",
        "connection": {
          "nodeId": "subtract_4",
          "outputKey": "result"
        }
      },
      "scale": {
        "type": "float",
        "label": "Scale"
      }
    },
    "outputs": {
      "output": {
        "type": "float",
        "label": "Output"
      }
    },
    "params": {
      "scale": 1,
      "outputType": "vec2"
    }
  },
  {
    "id": "smoothstep_6",
    "type": "smoothstep",
    "position": {
      "x": 1800,
      "y": 60
    },
    "inputs": {
      "value": {
        "type": "float",
        "label": "Value",
        "connection": {
          "nodeId": "length_5",
          "outputKey": "output"
        }
      },
      "edge0": {
        "type": "float",
        "label": "Edge 0"
      },
      "edge1": {
        "type": "float",
        "label": "Edge 1"
      }
    },
    "outputs": {
      "result": {
        "type": "float",
        "label": "Result"
      }
    },
    "params": {
      "edge0": 0.31,
      "edge1": 0.3,
      "outputType": "float"
    }
  },
  {
    "id": "floatToVec3_7",
    "type": "floatToVec3",
    "position": {
      "x": 2240,
      "y": 60
    },
    "inputs": {
      "input": {
        "type": "float",
        "label": "Float",
        "connection": {
          "nodeId": "smoothstep_6",
          "outputKey": "result"
        }
      }
    },
    "outputs": {
      "rgb": {
        "type": "vec3",
        "label": "Color"
      }
    },
    "params": {
      "outputType": "vec3"
    }
  },
  {
    "id": "colorPicker_8",
    "type": "colorPicker",
    "position": {
      "x": 40,
      "y": 412
    },
    "inputs": {},
    "outputs": {
      "rgb": {
        "type": "vec3",
        "label": "Color"
      },
      "r": {
        "type": "float",
        "label": "R"
      },
      "g": {
        "type": "float",
        "label": "G"
      },
      "b": {
        "type": "float",
        "label": "B"
      }
    },
    "params": {
      "color": [
        1,
        0.7,
        0.3
      ]
    }
  },
  {
    "id": "multiply_9",
    "type": "multiply",
    "position": {
      "x": 2680,
      "y": 60
    },
    "inputs": {
      "a": {
        "type": "vec3",
        "label": "A",
        "connection": {
          "nodeId": "floatToVec3_7",
          "outputKey": "rgb"
        }
      },
      "b": {
        "type": "vec3",
        "label": "B",
        "connection": {
          "nodeId": "colorPicker_8",
          "outputKey": "rgb"
        }
      }
    },
    "outputs": {
      "result": {
        "type": "vec3",
        "label": "Result"
      }
    },
    "params": {
      "b": 1,
      "outputType": "vec3"
    }
  },
  {
    "id": "output_10",
    "type": "output",
    "position": {
      "x": 3120,
      "y": 60
    },
    "inputs": {
      "color": {
        "type": "vec3",
        "label": "Color",
        "connection": {
          "nodeId": "multiply_9",
          "outputKey": "result"
        }
      }
    },
    "outputs": {},
    "params": {}
  }
];

export const SOFT_CIRCLE_OPTIMISED: GraphNode[] = [
  {
    "id": "fragCoord_1",
    "type": "fragCoord",
    "position": {
      "x": 40,
      "y": 60
    },
    "inputs": {},
    "outputs": {
      "coord": {
        "type": "vec2",
        "label": "Coord"
      }
    },
    "params": {}
  },
  {
    "id": "resolution_2",
    "type": "resolution",
    "position": {
      "x": 40,
      "y": 210
    },
    "inputs": {},
    "outputs": {
      "res": {
        "type": "vec2",
        "label": "Resolution"
      },
      "width": {
        "type": "float",
        "label": "Width"
      },
      "height": {
        "type": "float",
        "label": "Height"
      }
    },
    "params": {}
  },
  {
    "id": "colorPicker_8",
    "type": "colorPicker",
    "position": {
      "x": 40,
      "y": 412
    },
    "inputs": {},
    "outputs": {
      "rgb": {
        "type": "vec3",
        "label": "Color"
      },
      "r": {
        "type": "float",
        "label": "R"
      },
      "g": {
        "type": "float",
        "label": "G"
      },
      "b": {
        "type": "float",
        "label": "B"
      }
    },
    "params": {
      "color": [
        1,
        0.7,
        0.3
      ]
    }
  },
  {
    "id": "output_10",
    "type": "output",
    "position": {
      "x": 920,
      "y": 60
    },
    "inputs": {
      "color": {
        "type": "vec3",
        "label": "Color",
        "connection": {
          "nodeId": "block_1",
          "outputKey": "result"
        }
      }
    },
    "outputs": {},
    "params": {}
  },
  {
    "id": "block_1",
    "type": "exprNode",
    "position": {
      "x": 480,
      "y": 60
    },
    "inputs": {
      "pixel_coordinates": {
        "type": "vec2",
        "label": "pixel_coordinates",
        "connection": {
          "nodeId": "fragCoord_1",
          "outputKey": "coord"
        }
      },
      "resolution_res": {
        "type": "vec2",
        "label": "resolution_res",
        "connection": {
          "nodeId": "resolution_2",
          "outputKey": "res"
        }
      },
      "color_rgb": {
        "type": "vec3",
        "label": "color_rgb",
        "connection": {
          "nodeId": "colorPicker_8",
          "outputKey": "rgb"
        }
      },
      "subtract_b": {
        "type": "float",
        "label": "subtract_b"
      },
      "length_scale": {
        "type": "float",
        "label": "length_scale"
      },
      "smoothstep_edge0": {
        "type": "float",
        "label": "smoothstep_edge0"
      },
      "smoothstep_edge1": {
        "type": "float",
        "label": "smoothstep_edge1"
      }
    },
    "outputs": {
      "result": {
        "type": "vec3",
        "label": "Result (vec3)"
      }
    },
    "params": {
      "inputs": [
        {
          "name": "pixel_coordinates",
          "type": "vec2",
          "slider": null
        },
        {
          "name": "resolution_res",
          "type": "vec2",
          "slider": null
        },
        {
          "name": "color_rgb",
          "type": "vec3",
          "slider": null
        },
        {
          "name": "subtract_b",
          "type": "float",
          "slider": {
            "min": -10,
            "max": 10
          }
        },
        {
          "name": "length_scale",
          "type": "float",
          "slider": {
            "min": -10,
            "max": 10
          }
        },
        {
          "name": "smoothstep_edge0",
          "type": "float",
          "slider": {
            "min": -2,
            "max": 2
          }
        },
        {
          "name": "smoothstep_edge1",
          "type": "float",
          "slider": {
            "min": -2,
            "max": 2
          }
        }
      ],
      "outputType": "vec3",
      "lines": [
        {
          "lhs": "vec2 n1_result",
          "op": "=",
          "rhs": "pixel_coordinates / resolution_res"
        },
        {
          "lhs": "vec2 n2_result",
          "op": "=",
          "rhs": "n1_result - vec2(subtract_b)"
        },
        {
          "lhs": "float n3_output",
          "op": "=",
          "rhs": "length(n2_result) * length_scale"
        },
        {
          "lhs": "float n4_result",
          "op": "=",
          "rhs": "smoothstep(smoothstep_edge0, smoothstep_edge1, n3_output)"
        },
        {
          "lhs": "vec3 n5_rgb",
          "op": "=",
          "rhs": "vec3(n4_result)"
        },
        {
          "lhs": "vec3 n6_result",
          "op": "=",
          "rhs": "n5_rgb * color_rgb"
        }
      ],
      "result": "n6_result",
      "expr": "n6_result",
      "__foldedFrom": [
        "multiply_9",
        "floatToVec3_7",
        "smoothstep_6",
        "length_5",
        "subtract_4",
        "divide_3"
      ],
      "__foldedLabel": "Divide → Subtract → Length → Smoothstep → Float → Color → Multiply",
      "subtract_b": 0.5,
      "length_scale": 1,
      "smoothstep_edge0": 0.31,
      "smoothstep_edge1": 0.3
    }
  }
];
