/**
 * exampleIndex.ts — everything the UI needs to *list* the example graphs,
 * without loading them.
 *
 * The graphs themselves (exampleGraphs.ts, ~680 KB of source, 1,700 node
 * objects) are only needed when one is picked, so they live in their own
 * chunk behind `loadExampleGraphs()`. This module carries the labels, the
 * folder taxonomy, the default key, and the one graph that has to be
 * available synchronously at startup: the blank starter.
 */
import type { GraphNode } from '../types/nodeGraph';
import { ctp } from '../theme/palette';

export type ExampleGraph = { label: string; nodes: GraphNode[]; counter: number };

// A brand-new graph used to be just UV -> Output with nothing wired — a
// black screen with no hint of what to do next. A minimal UV -> Circle SDF
// -> distance -> glow -> Color chain gives every new project a visible,
// recognizable starting point instead.
export const BLANK_GRAPH: ExampleGraph = {
    label: '[ New ]',
    counter: 4,
    nodes: [
      { id: 'n1', type: 'uv', position: { x: 100, y: 240 }, inputs: {}, outputs: { uv: { type: 'vec2', label: 'UV' } }, params: {} },
      {
        id: 'n3', type: 'circleSDF', position: { x: 340, y: 240 },
        inputs: {
          position: { type: 'vec2', label: 'Position', connection: { nodeId: 'n1', outputKey: 'uv' } },
          radius:   { type: 'float', label: 'Radius' },
          offset:   { type: 'vec2', label: 'Offset' },
        },
        outputs: { distance: { type: 'float', label: 'Distance' } },
        params: { radius: 0.3, posX: 0.0, posY: 0.0 },
      },
      {
        id: 'n4', type: 'makeLight', position: { x: 580, y: 240 },
        inputs: {
          distance:   { type: 'float', label: 'Distance', connection: { nodeId: 'n3', outputKey: 'distance' } },
          brightness: { type: 'float', label: 'Brightness' },
        },
        outputs: { glow: { type: 'float', label: 'Glow' } },
        params: { brightness: 10.0 },
      },
      {
        id: 'n2', type: 'output', position: { x: 820, y: 240 },
        inputs: { color: { type: 'vec3', label: 'Color', connection: { nodeId: 'n4', outputKey: 'glow' } } },
        outputs: {}, params: {},
      },
    ],
  };

/** Key → label for every bundled example (generated from exampleGraphs.ts). */
export const EXAMPLE_INDEX: Record<string, { label: string }> = {
  blank: { label: BLANK_GRAPH.label },
  fractalRings: { label: "Fractal Rings" },
  forLoopRings: { label: "For Loop Rings" },
  exprRings: { label: "Expr Rings" },
  exprOrbit: { label: "Expr Orbit" },
  animatedPalette: { label: "Animated Palette" },
  shapeShowcase: { label: "Shape Showcase" },
  toneMapDemo: { label: "Tone Map — ACES" },
  glowCircle: { label: "Glowing Circle" },
  fbmLandscape: { label: "FBM Landscape" },
  angularGradient: { label: "Angular Gradient" },
  raymarchSpheres: { label: "Raymarch Spheres" },
  gravitationalLens: { label: "Gravity Lens" },
  glowShape: { label: "Glow Shape" },
  chladniFieldQuickDemo: { label: "Chladni Field (Quick)" },
  chladniComposableDemo: { label: "Chladni (Composable)" },
  waveTermManualMixDemo: { label: "Wave Term (Manual Mix)" },
  quantizeChladniDemo: { label: "Quantize → Chladni Field" },
  chladniFieldCircularDemo: { label: "Chladni Field (Circular)" },
  chladniModeFreqDemo: { label: "Chladni Mode Frequency" },
  fractalRingsGroup: { label: "Fractal Rings (Group)" },
  noiseFloatDemo: { label: "Noise Float — Wobbly Circle" },
  hsvDemo: { label: "HSV — Hue Rotation" },
  posterizeDemo: { label: "Posterize" },
  desaturateDemo: { label: "Desaturate" },
  remapDemo: { label: "Remap — Noise-Driven Radius" },
  groupCarryRings: { label: "Group: Fractal Rings (Carry)" },
  groupCarryZoom: { label: "Group: Zoom Rings (Carry)" },
  groupCarryFBM: { label: "Group: FBM Octaves (Carry)" },
  groupCarryDomainWarp: { label: "Group: Domain Warp (Carry)" },
  groupCarryPowerFold: { label: "Group: Power Fold (Carry)" },
  agxToneDemo: { label: "Tone Map — AgX" },
  lumaGrainDemo: { label: "Film Grain" },
  temporalGrainDemo: { label: "Temporal Grain" },
  newtonFractalZ5: { label: "Newton z⁵−1" },
  colorRampDemo: { label: "Color Ramp" },
  blackbodyDemo: { label: "Blackbody" },
  waveTextureDemo: { label: "Wave Texture" },
  magicTextureDemo: { label: "Magic Texture" },
  gridDemo: { label: "Grid / Checker" },
  blendModesDemo: { label: "Blend Modes — Screen" },
  colorRampFBM: { label: "Color Ramp: FBM Terrain" },
  colorRampWave: { label: "Color Ramp: Wave Rings" },
  blackbodyStar: { label: "Blackbody: Star Spectrum" },
  waveInterference: { label: "Wave Interference" },
  waveBands: { label: "Wave Bands" },
  gridCellPattern: { label: "Grid: Cell UV Pattern" },
  gridChecker: { label: "Grid: Checker" },
  gridMagic: { label: "Grid: Magic Cells" },
  complexPowFlower: { label: "Complex Power Flower" },
  luminanceTint: { label: "Luminance: Grey & Tint" },
  sphereScene3D: { label: "3D: Sphere" },
  torusScene3D: { label: "3D: Torus" },
  twoShapes3D: { label: "3D: Sphere + Box" },
  infiniteBoxes3D: { label: "3D: Infinite Boxes" },
  helloSphere3D: { label: "3D: Hello Sphere" },
  shapesAndGround3D: { label: "3D: Shapes + Ground" },
  infiniteFalling3D: { label: "3D: Infinite Falling" },
  spiralWorld3D: { label: "3D: Spiral World" },
  softMetaballs3D: { label: "3D: Soft Metaballs" },
  normalColor3D: { label: "3D: Normal Color" },
  depthIterAO3D: { label: "3D: Depth + Iter AO" },
  neonFloorGrid: { label: "Neon Floor Grid" },
  spectralLens: { label: "Spectral Lens" },
  alphaLayerDemo: { label: "Alpha Layer Demo" },
  particleFlowDrift: { label: "Particles: Flow Field" },
  particleSpiralVortex: { label: "Particles: Spiral Vortex" },
  particleOrbitCloud: { label: "Particles: Orbit Cloud" },
  particleRain: { label: "Particles: Rain" },
  gaussianBlurDemo: { label: "Gaussian Blur" },
  motionBlurTrails: { label: "Motion Blur Trails" },
  tiltShiftScene: { label: "Tilt-Shift" },
  lensBokeh: { label: "Lens Blur Bokeh" },
  weightedNoiseOctaves: { label: "Weighted Noise Octaves" },
  weightedSdfBlend: { label: "Weighted SDF Blend" },
  fractalGlowBlur: { label: "Fractal + Blur Glow" },
  ray3DVignette: { label: "3D Sphere + Vignette" },
  swirlRay3D: { label: "Swirl + 3D Scene" },
  kaleido3DBox: { label: "Kaleido + 3D Box" },
  translate3D: { label: "3D: Translate" },
  rotate3D: { label: "3D: Rotate" },
  fold3D: { label: "3D: Fold Symmetry" },
  sinWarp3D: { label: "3D: Sin Warp" },
  repeat3D: { label: "3D: Repeat / Tile" },
  planeSDF3D: { label: "3D: Ground Plane" },
  rayMarchOutputs3D: { label: "3D: Ray March Outputs" },
  mlgWiggleTunnel: { label: "MLG: Wiggle Tunnel" },
  sdfPolarRepeat: { label: "3D: Polar Repeat — Radial Symmetry" },
  sdfSmoothMetaballs: { label: "3D: Metaballs — Smooth Union Chain" },
  sdfBend3D: { label: "3D: Bend Deform" },
  sdfIntersectDemo: { label: "3D: Boolean Intersect" },
  mirroredTileRepeat: { label: "2D: Mirrored Tiles" },
  angularFlowerRepeat: { label: "2D: Angular Repeat" },
  angularGearRepeat: { label: "2D: Angular Gear" },
  limitedRepeatGrid: { label: "2D: Limited Grid" },
  sdCrossScene3D: { label: "3D: SD Cross" },
  infinitePillars3D: { label: "3D: Infinite Pillars" },
  aoSphere: { label: "3D Lighting: AO Sphere" },
  conditionalCircle: { label: "Conditionals / Hard Circle" },
  conditionalGlowRing: { label: "Conditionals / Soft Glow Ring" },
  conditionalAnimThreshold: { label: "Conditionals / Animated Threshold" },
  conditionalBrightnessGate: { label: "Conditionals / Brightness Gate" },
  conditionalApproxMatch: { label: "Conditionals / Approx Match" },
  gyroidWarped: { label: "3D: Gyroid + Domain Warp" },
  mirrorFoldSpheres: { label: "3D: Mirror Fold Spheres" },
  mirrorFoldBoxes: { label: "3D: Mirror Fold Boxes" },
  vec3SwizzlePalette: { label: "Vec3 Swizzle: Color Cycle" },
  vec2SwizzleUV: { label: "Vec2 Swizzle: UV Reflection" },
  domainWarpSphere: { label: "3D: Domain Warp Sphere" },
  swizzle3DNormalMap: { label: "3D: Swizzle Normal Colors" },
  swizzle3DPosGradient: { label: "3D: Swizzle Position Gradient" },
  glowMarcher: { label: "3D: Glow Marcher" },
  volHollowShell: { label: "Volumetric: Hollow Shell" },
  volTorus: { label: "Volumetric: Glowing Torus" },
  volRepeatLattice: { label: "Volumetric: Repeat Lattice" },
  volOctahedron: { label: "Volumetric: Octahedron" },
  volAnimatedRepeat: { label: "Volumetric: Animated Repeat" },
  dofOrbitOrbs: { label: "DoF: Orbit Orbs" },
  dofForwardDepth: { label: "DoF: Forward Depth" },
  jitterFogSphere: { label: "Jitter: Smooth Volumetric Fog" },
  jitterTorusCloud: { label: "Jitter: Torus Cloud" },
  phaseHGForwardCloud: { label: "Phase HG: Forward Scatter Cloud" },
  phaseHGBacklit: { label: "Phase HG: Backlit Haze" },
  fresnelSchlickRim: { label: "Fresnel Schlick: Rim Glow" },
  fresnelSchlickTwoTone: { label: "Fresnel Schlick: Two-Tone Surface" },
  refractDirFakeGlass: { label: "Refract Dir: Fake Glass" },
  refractDirDispersion: { label: "Refract Dir: Chromatic Dispersion" },
  dofDepthBlur: { label: "Depth of Field: Post-Process Blur" },
  ringGlow: { label: "Ring Glow" },
  sphereFaceLight: { label: "Sphere Face Light" },
  matrixAnisotropicScale: { label: "Matrix: Anisotropic Scale" },
  matrixShear: { label: "Matrix: Shear" },
  matrixXZYZ: { label: "Matrix: 3D Dual-Axis Rotation" },
  matrixColorGrade: { label: "Matrix: RGB Color Grade" },
  cgHueRotate: { label: "Color Grade: Hue Rotate" },
  cgLiftGammaGain: { label: "Color Grade: Lift / Gamma / Gain" },
  cgChain: { label: "Color Grade: Full Chain" },
  glassPhysical: { label: "Glass 3D: Physical" },
  spectralPrism: { label: "Spectral Prism (rygcbv)" },
  blinnPhongSphere: { label: "Blinn-Phong: Lit Sphere" },
  glassMetaballs: { label: "Glass Metaballs" },
  glassRoundBox: { label: "Glass Rounded Box" },
  glassOrbTrio: { label: "Glass Orb Trio (Spectral)" },
  glassLavaBlob: { label: "Glass Lava Blob" },
  halftoneNoise: { label: "Halftone Noise" },
  cmykNoise: { label: "CMYK Halftone" },
  ringHalftone: { label: "Ring Halftone" },
  glassSceneOrbPillars: { label: "Glass Scene: Orb + Pillars" },
  glassSceneTorusBlobs: { label: "Glass Scene: Torus + Blobs" },
  glassIridescentRim: { label: "Glass: Iridescent Rim" },
  glassTintedReflection: { label: "Glass: Tinted Reflection" },
  glassFlatBlend: { label: "Glass: Flat Blend" },
  glassSceneLensVoid: { label: "Glass Scene: Lens + Void" },
  giSphereGround: { label: "GI: Sphere & Ground" },
  giGoldTorus: { label: "GI: Gold Torus" },
  giBlobCluster: { label: "GI: Blob Cluster" },
  giBoxFrame: { label: "GI: Box Frame" },
  gridBasic: { label: "Grid: Rings" },
  gridCircles: { label: "Grid: Color Circles" },
  gridWave: { label: "Grid: Wave" },
  gridNeighborDots: { label: "Grid: Pulse" },
  gridGravity: { label: "Grid: Gravity" },
  gridMetaballs: { label: "Grid: Metaballs" },
  gridBreathing: { label: "Grid: Breathing" },
  gridDensityWave: { label: "Grid: Density Wave" },
  gridLavaLamp: { label: "Grid: Lava Lamp" },
  gridOnionRings: { label: "Grid: Onion Rings" },
  gridIronFilings: { label: "Grid: Iron Filings" },
  gridFreqColumns: { label: "Grid: Freq Columns" },
  gridNeighborDisplaced: { label: "Grid: Scatter" },
};

// The default graph to load on startup
export const DEFAULT_EXAMPLE = 'fractalRings';

/** Loads the full example set on first use; the module system caches it after that. */
export async function loadExampleGraphs(): Promise<Record<string, ExampleGraph>> {
  const mod = await import('./exampleGraphs');
  return mod.EXAMPLE_GRAPHS;
}

// ── Example folders ──────────────────────────────────────────────────────────
// Groups example keys into categories for the desktop NodePalette's Examples
// browser and the mobile examples picker (App.tsx) — one taxonomy, shared, so
// the two surfaces never drift.
export const EXAMPLE_FOLDERS: Array<{ label: string; color: string; keys: string[] }> = [
  { label: 'GI Lighting',     color: ctp.green, keys: ['giSphereGround','giGoldTorus','giBlobCluster','giBoxFrame'] },
  { label: '3D Lighting',     color: '#f9c468', keys: ['aoSphere','phaseHGForwardCloud','phaseHGBacklit','fresnelSchlickRim','fresnelSchlickTwoTone','refractDirFakeGlass','refractDirDispersion','glassPhysical','spectralPrism','blinnPhongSphere','glassMetaballs','glassRoundBox','glassOrbTrio','glassLavaBlob','glassSceneOrbPillars','glassSceneTorusBlobs','glassSceneLensVoid','glassIridescentRim','glassTintedReflection','glassFlatBlend'] },
  { label: '3D SDF',          color: ctp.sky, keys: ['sdfPolarRepeat','sdfSmoothMetaballs','sdfBend3D','sdfIntersectDemo','sdCrossScene3D','infinitePillars3D','spiralWorld3D','gyroidWarped','mirrorFoldSpheres','mirrorFoldBoxes','domainWarpSphere','swizzle3DNormalMap','swizzle3DPosGradient'] },
  { label: 'Blur & Lens',     color: ctp.blue, keys: ['gaussianBlurDemo','motionBlurTrails','tiltShiftScene','lensBokeh','dofOrbitOrbs','dofForwardDepth','dofDepthBlur'] },
  { label: 'Color & Lighting',color: ctp.peach, keys: ['glowCircle','blackbodyDemo','blendModesDemo','toneMapDemo','angularGradient','shapeShowcase','fbmLandscape','spectralLens','vec3SwizzlePalette','vec2SwizzleUV'] },
  { label: 'Color Grading',   color: '#f9a86b', keys: ['cgHueRotate','cgLiftGammaGain','cgChain'] },
  { label: 'Grid',            color: ctp.sky, keys: ['gridBasic','gridCircles','gridWave','gridNeighborDots','gridNeighborDisplaced','gridGravity','gridMetaballs','gridBreathing','gridDensityWave','gridLavaLamp','gridOnionRings','gridIronFilings','gridFreqColumns'] },
  { label: 'Halftone',        color: '#a6e3d5', keys: ['halftoneNoise','cmykNoise','ringHalftone'] },
  { label: 'Iterated Groups', color: ctp.green, keys: ['groupCarryRings','groupCarryZoom','groupCarryFBM','groupCarryDomainWarp','groupCarryPowerFold'] },
  { label: 'Matrix',          color: '#f5c842', keys: ['matrixAnisotropicScale','matrixShear','matrixXZYZ','matrixColorGrade'] },
  { label: 'Patterns',        color: ctp.green, keys: ['angularFlowerRepeat','angularGearRepeat','ringGlow','sphereFaceLight'] },
  { label: 'Physics',         color: ctp.teal, keys: ['chladniFieldQuickDemo','chladniFieldCircularDemo','chladniComposableDemo','waveTermManualMixDemo','quantizeChladniDemo','chladniModeFreqDemo'] },
  { label: 'Rings',           color: ctp.red, keys: ['fractalRings','exprRings','fractalRingsGroup','exprOrbit'] },
  { label: 'Space & Texture', color: ctp.flamingo, keys: ['waveTextureDemo','waveInterference','waveBands','magicTextureDemo','gridDemo','gridCellPattern','gridChecker','gridMagic','mirroredTileRepeat','limitedRepeatGrid','mlgWiggleTunnel'] },
  { label: 'Volumetric',      color: '#f5a97f', keys: ['glowMarcher','volHollowShell','volTorus','volRepeatLattice','volOctahedron','volAnimatedRepeat','jitterFogSphere','jitterTorusCloud'] },
];
