/**
 * The command language's sentence corpus (doCommands.test.ts): a sentence, the scratch graph it
 * runs on (suggestions/doScratch.ts), the nodes selected first, and the clauses it reads as —
 * each clause's verb, with !error or !pick when it is refused or waits for a pick.
 */
import type { ScratchId } from '../../lang/commands';

export const CORPUS: Array<[text: string, on: ScratchId, selected: string[] | undefined, expected: string]> = [
  // The brief's sentences
  ['create a ring with falloff 0.3, colour it with a palette by the length of the space, multiply it by the circle, then output it', 'circle', undefined, 'create colour combine output'],
  ['disconnect the current output, add it to the noise, and output the result', 'mixed', undefined, 'disconnect combine output'],
  ['set the glow falloff to 8', 'glow', undefined, 'set'],
  ['make the circle bigger', 'circle', undefined, 'adjust'],
  ['switch the noise to fbm', 'mixed', undefined, 'replace!error'],
  ['switch the noise to voronoi', 'noise', undefined, 'replace'],
  // Single build phrases (the phrase language, whole)
  ['circle in the middle with a glow, falloff 8', 'empty', undefined, 'build'],
  ['add rings', 'circle', ['c'], 'build'],
  ['make it repeat 6 times around', 'circle', ['c'], 'build'],
  ['twist the space 0.5', 'circle', ['c'], 'build'],
  ['tone map it', 'noise', ['p'], 'build'],
  ['heart at the top left with rings', 'empty', undefined, 'build'],
  ['circle with a glow then tone map it', 'circle', ['c'], 'build'],
  ['mix these colours', 'mixed', ['p', 'g'], 'build'],
  ['blend it with a box', 'circle', ['c'], 'build'],
  ['circel with a glwo', 'empty', undefined, 'build'],
  ['add grain 0.1', 'noise', ['p'], 'build'],
  ['screen blend', 'noise', ['p'], 'build'],
  ['duplicate 4 times', 'circle', ['c'], 'build'],
  ['colour it', 'noise', ['f'], 'build'],
  ['turn 45 degrees', 'circle', ['c'], 'build'],
  ['flibbertigibbet', 'empty', undefined, 'build!error'],
  // Build phrases that name their node
  ['glow the circle', 'mixed', undefined, 'build'],
  ['add rings to the circle', 'mixed', undefined, 'build'],
  ['polar the noise', 'noise', undefined, 'build'],
  ['tone map the palette', 'noise', undefined, 'build'],
  ['outline the circle width 0.02', 'glow', undefined, 'build'],
  // Create
  ['create a noise', 'empty', undefined, 'create'],
  ['create a voronoi', 'empty', undefined, 'create'],
  ['add a star at the top left', 'circle', undefined, 'create'],
  ['create a ring with falloff 0.3', 'empty', undefined, 'create'],
  ['create a palette', 'empty', undefined, 'create'],
  ['create a time', 'empty', undefined, 'create'],
  ['make a heart with rings', 'empty', undefined, 'create'],
  ['create a flurble', 'empty', undefined, 'create!error'],
  ['create a noise, then output it', 'empty', undefined, 'create output'],
  ['create a circle, glow it falloff 4, then output it', 'empty', undefined, 'create build output'],
  // Connect / disconnect / reconnect
  ['connect the glow to the output', 'mixed', undefined, 'connect'],
  ['connect the noise to the tint of the glow', 'mixed', undefined, 'connect'],
  ["connect the noise to the glow's tint", 'mixed', undefined, 'connect'],
  ['plug the box into the fill', 'twoShapes', undefined, 'connect'],
  ['wire the circle into the output', 'glow', undefined, 'connect'],
  ['connect the palette to the circle', 'mixed', undefined, 'connect'],
  ['connect the glow to the glow', 'glow', undefined, 'connect!error'],
  ['connect the glow to the frobnicator of the output', 'glow', undefined, 'connect!error'],
  ['disconnect the current output', 'noise', undefined, 'disconnect'],
  ['disconnect the noise from the palette', 'noise', undefined, 'disconnect'],
  ['disconnect the position of the circle', 'circle', undefined, 'disconnect'],
  ["unplug the circle's position", 'circle', undefined, 'disconnect'],
  ['disconnect the output', 'noise', undefined, 'disconnect'],
  ['disconnect the glow', 'mixed', undefined, 'disconnect!error'],
  ['reconnect the circle to the output', 'glow', undefined, 'reconnect'],
  ['rewire the noise to the output', 'noise', undefined, 'reconnect'],
  // Insert
  ['insert a tone map between the palette and the output', 'noise', undefined, 'insert'],
  ['insert a tone map between the output and the palette', 'noise', undefined, 'insert'],
  ['insert an abs after the circle', 'circle', undefined, 'insert'],
  ['put a smoothstep before the palette', 'noise', undefined, 'insert'],
  ['insert a luminance between the palette and the output', 'noise', undefined, 'insert'],
  ['insert a tone map between the noise and the output', 'noise', undefined, 'insert!error'],
  ['insert a wibble after the circle', 'circle', undefined, 'insert!error'],
  // Combine
  ['multiply the output with the noise', 'mixed', undefined, 'combine'],
  ['add the glow to the palette', 'mixed', undefined, 'combine'],
  ['mix the palette with the glow by 0.3', 'mixed', undefined, 'combine'],
  ['multiply it by 2', 'noise', ['p'], 'combine'],
  ['multiply the noise by red', 'noise', undefined, 'combine'],
  ['subtract the circle from the noise', 'mixed', undefined, 'combine'],
  ['union the circle with the box', 'twoShapes', undefined, 'combine'],
  ['blend the circle with the box', 'twoShapes', undefined, 'combine'],
  ['cut the box from the circle', 'twoShapes', undefined, 'combine'],
  ['screen the glow over the palette', 'mixed', undefined, 'combine'],
  ['union the palette with the circle', 'mixed', undefined, 'combine!error'],
  ['multiply the circle by the square', 'mixed', undefined, 'combine!error'],
  // Output
  ['output the glow', 'mixed', undefined, 'output'],
  ['show the noise', 'noise', undefined, 'output'],
  ['output the node before the output', 'noise', undefined, 'output'],
  ['output the output', 'noise', undefined, 'output!error'],
  // Replace
  ['turn the circle into a box', 'circle', undefined, 'replace'],
  ['replace the palette with a stops palette', 'noise', undefined, 'replace'],
  ['swap the circle for a heart', 'circle', undefined, 'replace'],
  ['change the noise to voronoi', 'noise', undefined, 'replace'],
  ['switch the circle to a palette', 'circle', undefined, 'replace!error'],
  // Delete / rename / duplicate
  ['delete the glow', 'mixed', undefined, 'delete'],
  ['remove all circles', 'twoShapes', undefined, 'delete'],
  ['delete the circle and the box', 'twoShapes', undefined, 'delete'],
  ['get rid of these', 'twoShapes', ['a', 'b'], 'delete'],
  ['rename the glow to "Halo"', 'glow', undefined, 'rename'],
  ['call the noise "Clouds"', 'noise', undefined, 'rename'],
  ['rename "Clouds" to "Mist"', 'noise', undefined, 'rename'],
  ['rename "Mist" to "Fog"', 'noise', undefined, 'rename!error'],
  ['duplicate the circle', 'circle', undefined, 'duplicate'],
  ['copy the glow, then set its falloff to 3', 'glow', undefined, 'duplicate set'],
  // Set
  ['set the radius of the circle to 0.4', 'circle', undefined, 'set'],
  ["set the circle's radius to 0.2", 'circle', undefined, 'set'],
  ['set the glow tint to cyan', 'glow', undefined, 'set'],
  ['set the radius to 0.1', 'circle', ['c'], 'set'],
  ['set the glow mode to haze', 'glow', undefined, 'set'],
  ['change the falloff of the glow to 4', 'glow', undefined, 'set'],
  ['set the circle to 0.25', 'circle', undefined, 'set'],
  ['set the glow wobble to 3', 'glow', undefined, 'set!error'],
  ['set the glow falloff to purple', 'glow', undefined, 'set!error'],
  // Adjust
  ['make the glow much wider', 'glow', undefined, 'adjust'],
  ['make the circle a bit smaller', 'circle', undefined, 'adjust'],
  ['increase the radius of the circle by 0.1', 'circle', undefined, 'adjust'],
  ['double the falloff of the glow', 'glow', undefined, 'adjust'],
  ['halve the radius of the circle', 'circle', undefined, 'adjust'],
  ['make the noise faster', 'noise', undefined, 'adjust'],
  ['lower the glow falloff', 'glow', undefined, 'adjust'],
  ['make it bigger', 'circle', ['c'], 'adjust'],
  // Group / select
  ['group the circle and the glow as "Neon"', 'glow', undefined, 'group'],
  ['group these', 'twoShapes', ['a', 'b'], 'group'],
  ['group the circle, then delete the glow', 'glow', undefined, 'group!error delete'],
  ['group the output', 'glow', undefined, 'group!error'],
  ['select all circles', 'twoShapes', undefined, 'select'],
  ['select the node before the output', 'noise', undefined, 'select'],
  ['select the node after the noise', 'noise', undefined, 'select'],
  // Colour
  ['colour it with a palette by the length of the space', 'glow', ['g'], 'colour'],
  ['colour the noise with a palette', 'mixed', undefined, 'colour'],
  ['colour the glow by time', 'glow', undefined, 'colour'],
  ['colour the circle by the angle', 'circle', undefined, 'colour'],
  ['color the glow with a palette by the noise', 'mixed', undefined, 'colour'],
  ['colour the glow by the x of the space', 'glow', undefined, 'colour'],
  // References and ambiguity
  ['make the first circle bigger', 'twoShapes', undefined, 'adjust'],
  ['delete circle 1', 'twoShapes', undefined, 'delete'],
  ['make the last shape bigger', 'twoShapes', undefined, 'adjust!error'],
  ['output the glow, then rename it to "Rim"', 'mixed', undefined, 'output rename'],
  ['create a circle, then make the circle bigger', 'circle', undefined, 'create adjust'],
  ['make the circle bigger', 'twoCircles', undefined, 'adjust!pick'],
  ['make the circle bigger', 'twoCircles', ['b'], 'adjust'],
  ['make the second circle bigger', 'twoCircles', undefined, 'adjust'],
  ['delete all circles', 'twoCircles', undefined, 'delete'],
  ['insert an abs between the circle and the fill', 'twoCircles', undefined, 'insert!pick'],
  ['output the circle, then group these', 'twoCircles', ['a', 'b'], 'output!pick group'],
  ['connect the uv to the circle', 'twoShapes', undefined, 'connect!error'],
  // Did-you-mean and partial reads
  ['conect the glow to the output', 'mixed', undefined, 'build!error'],
  ['create a noise, frobnicate it, then output it', 'empty', undefined, 'create build!error output!error'],
  ['create a noise, frobnicate it, then output the noise', 'empty', undefined, 'create build!error output'],
  ['create a nosie', 'empty', undefined, 'create!error'],
  ['delete the sphere', 'circle', undefined, 'delete'],
  ['delete the torch', 'circle', undefined, 'delete!error'],
];
