import type { NodeDefinition } from '../../types/nodeGraph';

/** Most passes an iterated group makes (64: enough to visit every row of a small dataset). */
/** Iterations' ceiling (a Play control on it compiles the loop this far; implementation guide, small tasks). */
export const MAX_GROUP_ITERATIONS = 128;

/**
 * Group node — a collapsed subgraph.
 *
 * The node's inputs/outputs are set dynamically at creation time from the
 * SubgraphData.inputPorts and outputPorts.  The compiler inlines the subgraph
 * code at the group node's position in the topological order.
 *
 * Stored in node.params.subgraph as a SubgraphData object (see nodeGraph.ts).
 * The compiler special-cases this type; generateGLSL is a stub.
 */
export const GroupNode: NodeDefinition = {
  type: 'group',
  label: 'Group',
  category: 'Utility',
  description:
    'A collapsed group of nodes whose subgraph is compiled inline. ' +
    'Use the "Group nodes" action to create one from a selection.',

  // Populated dynamically per instance — the static def has no sockets.
  inputs: {},
  outputs: {},

  defaultParams: { iterations: 1 },
  paramDefs: {
    iterations: { label: 'Iterations', type: 'float', min: 1, max: MAX_GROUP_ITERATIONS, step: 1 },
  },

  // Stub — real code is generated by graphCompiler when it encounters type === 'group'
  generateGLSL: () => ({ code: '', outputVars: {} }),
};
