/**
 * scene3d.ts — Composable 3D scene system (Phase 3, V2)
 *
 * Three nodes work together:
 *
 *  ScenePosNode  — outputs the ray position `p` (vec3) inside a scene function.
 *  SceneGroupNode — a group-like container whose subgraph is compiled as a named
 *                   GLSL function `float mapScene_<id>(vec3 p)`.  Its output is
 *                   of type `scene3d` — just the function name string on the wire.
 *  RayMarchNode   — camera + march only, outputs raw data: dist, depth, normal, iter, hit.
 *  RayMarchLitNode — camera + march + AO + shadows + PBR diffuse, outputs color + raw data.
 *  RayRenderNode  — legacy node kept for backward compatibility with saved graphs.
 *
 * Compiler contract (shaderAssembler.ts):
 *   - When a node of type 'sceneGroup' is encountered, its subgraph is compiled
 *     into a standalone GLSL function and added to the functions set.
 *   - ScenePosNode inside a sceneGroup outputs the literal string 'p' (the func arg).
 *   - The sceneGroup's `scene3d` output var is the function name, e.g. `mapScene_<id>`.
 *   - RayMarchNode/RayMarchLitNode receive this as their `scene` inputVar and plug it into the march loop.
 */
import type { NodeDefinition, GraphNode } from '../../types/nodeGraph';
import { p } from './helpers';

// ─── ScenePosNode ──────────────────────────────────────────────────────────────
// Inside a sceneGroup, outputs the ray march position `p` (the function parameter).
// The compiler replaces its output var with the literal string 'p' when inside
// a sceneGroup compilation context.  See shaderAssembler.ts sceneGroup handler.

export const ScenePosNode: NodeDefinition = {
  type: 'scenePos', label: 'Scene Pos', category: '3D Scene',
  description: 'Inside a Scene Group: outputs the current ray march position (vec3 p). Connect to SDF primitive inputs.',
  anchored: true,
  inputs: {},
  outputs: { pos: { type: 'vec3', label: 'Position' } },
  defaultParams: {},
  paramDefs: {},
  generateGLSL: (node: GraphNode) => {
    const id = node.id;
    // In a sceneGroup context the compiler pre-registers this node's output as 'p'.
    // This fallback is used when the node is compiled outside a sceneGroup (preview etc.).
    return {
      code: `    vec3 ${id}_pos = vec3(0.0);\n`,
      outputVars: { pos: `${id}_pos` },
    };
  },
};

// ─── SceneGroupNode ────────────────────────────────────────────────────────────
// A container node (like GroupNode) whose subgraph is compiled as a GLSL function.
// The compiler special-cases type === 'sceneGroup' exactly like type === 'group',
// but emits a named function instead of inlining code.

export const SceneGroupNode: NodeDefinition = {
  type: 'sceneGroup', label: 'Scene Group', category: '3D Scene',
  description: 'Wrap SDF nodes into a composable 3D scene. Inside a March Loop Group: connect the warp chain → pos input to specify the evaluation point. ScenePos inside always gives the function argument "p".',
  // pos input: when inside a MarchLoopGroup body, connects to the warp chain output.
  // The compiler uses this connection to set the call-site argument in the march loop.
  // ScenePos inside the subgraph still resolves to 'p' regardless.
  inputs: {
    pos: { type: 'vec3', label: 'Position' },
  },
  outputs: { scene: { type: 'scene3d', label: 'Scene' } },
  defaultParams: {},
  paramDefs: {},
  // Stub — real code is generated by the compiler when it encounters type === 'sceneGroup'
  generateGLSL: () => ({ code: '', outputVars: {} }),
};

// ─── MarchCameraNode ──────────────────────────────────────────────────────────
// Camera setup for ray marching. Outputs ray origin (ro) and ray direction (rd).
// Pair with MarchLoopGroupNode: camera → march loop → coloring nodes.

export const MarchCameraNode: NodeDefinition = {
  type: 'marchCamera', label: 'March Camera', category: '3D Scene',
  description: 'Camera setup for ray marching. Outputs ray origin (ro) and ray direction (rd). Connect to a March Loop Group.',
  inputs: {
    uv:           { type: 'vec2',  label: 'UV' },
    time:         { type: 'float', label: 'Time' },
    camDist:      { type: 'float', label: 'Cam Distance' },
    camAngle:     { type: 'float', label: 'Cam Angle' },
    camElevation: { type: 'float', label: 'Elevation' },
    rotSpeed:     { type: 'float', label: 'Rot Speed' },
    fov:          { type: 'float', label: 'FOV' },
    targetX:      { type: 'float', label: 'Target X' },
    targetY:      { type: 'float', label: 'Target Y' },
    targetZ:      { type: 'float', label: 'Target Z' },
  },
  outputs: {
    ro: { type: 'vec3', label: 'Ray Origin' },
    rd: { type: 'vec3', label: 'Ray Dir' },
  },
  defaultParams: {
    camDist: 3.0, camAngle: 0.6, camElevation: 0.3, rotSpeed: 0.0, fov: 1.5,
    targetX: 0.0, targetY: 0.0, targetZ: 0.0, aperture: 0.0, focalDist: 3.0,
  },
  paramDefs: {
    camDist:      { label: 'Cam Dist',   type: 'float' as const, min: 0.1,  max: 20.0, step: 0.05, hint: 'Distance from the camera to the target point.' },
    camAngle:     { label: 'Angle',      type: 'float' as const, min: 0.0,  max: 6.28, step: 0.02, hint: 'Horizontal orbit angle (radians) around Y axis.' },
    camElevation: { label: 'Elevation',  type: 'float' as const, min: -1.5, max: 1.5,  step: 0.02, hint: 'Vertical angle: 0 = horizon, positive = above, negative = below.' },
    rotSpeed:     { label: 'Rot Speed',  type: 'float' as const, min: 0.0,  max: 2.0,  step: 0.01, hint: 'Auto-rotation speed. 0 = static.' },
    fov:          { label: 'FOV',        type: 'float' as const, min: 0.5,  max: 3.14, step: 0.05, hint: 'Field of view. Higher = wider angle.' },
    targetX:      { label: 'Target X',   type: 'float' as const, min: -20.0, max: 20.0, step: 0.05, hint: 'X position of the look-at target.' },
    targetY:      { label: 'Target Y',   type: 'float' as const, min: -20.0, max: 20.0, step: 0.05, hint: 'Y position of the look-at target.' },
    targetZ:      { label: 'Target Z',   type: 'float' as const, min: -20.0, max: 20.0, step: 0.05, hint: 'Z position of the look-at target.' },
    aperture:     { label: 'Aperture',   type: 'float' as const, min: 0.0,  max: 0.5,  step: 0.005, hint: 'Lens aperture radius. 0 = pinhole (no blur). Higher = more bokeh.' },
    focalDist:    { label: 'Focal Dist', type: 'float' as const, min: 0.1,  max: 50.0, step: 0.1,   hint: 'Distance from camera at which the scene is perfectly sharp.' },
  },
  generateGLSL: (node: GraphNode, inputVars) => {
    const id           = node.id;
    const uv           = inputVars.uv           || 'g_uv';
    const time         = inputVars.time         || 'u_time';
    const camDist      = inputVars.camDist      || p(node.params.camDist,      3.0);
    const camAngle     = inputVars.camAngle     || p(node.params.camAngle,     0.6);
    const camElevation = inputVars.camElevation || p(node.params.camElevation, 0.3);
    const rotSpeed     = inputVars.rotSpeed     || p(node.params.rotSpeed,     0.0);
    const fov          = inputVars.fov          || p(node.params.fov,          1.5);
    const targetX      = inputVars.targetX      || p(node.params.targetX,      0.0);
    const targetY      = inputVars.targetY      || p(node.params.targetY,      0.0);
    const targetZ      = inputVars.targetZ      || p(node.params.targetZ,      0.0);
    const aperture     = inputVars.aperture     || p(node.params.aperture,     0.0);
    const focalDist    = inputVars.focalDist    || p(node.params.focalDist,    3.0);

    const code = [
      `    float ${id}_ang   = ${camAngle} + ${time} * ${rotSpeed};\n`,
      `    float ${id}_elev  = ${camElevation};\n`,
      `    vec3  ${id}_ta    = vec3(${targetX}, ${targetY}, ${targetZ});\n`,
      `    vec3  ${id}_horiz = vec3(sin(${id}_ang), 0.0, cos(${id}_ang));\n`,
      `    vec3  ${id}_ro0   = ${id}_ta + ${camDist} * (cos(${id}_elev)*${id}_horiz + sin(${id}_elev)*vec3(0.0,1.0,0.0));\n`,
      `    vec3  ${id}_fwd   = normalize(${id}_ta - ${id}_ro0);\n`,
      `    vec3  ${id}_cup   = normalize(-sin(${id}_elev)*${id}_horiz + cos(${id}_elev)*vec3(0.0,1.0,0.0));\n`,
      `    vec3  ${id}_rgt   = normalize(cross(${id}_cup, ${id}_fwd));\n`,
      `    vec3  ${id}_up2   = cross(${id}_fwd, ${id}_rgt);\n`,
      // Pinhole ray direction
      `    vec3  ${id}_rd0   = normalize(${uv}.x * ${id}_rgt + ${uv}.y * ${id}_up2 + ${fov} * ${id}_fwd);\n`,
      // Thin-lens DoF: hash of uv+time → disk sample → shift ro, redirect rd through focal point
      `    float ${id}_h1    = fract(sin(dot(${uv} + ${time}, vec2(127.1, 311.7))) * 43758.5453);\n`,
      `    float ${id}_h2    = fract(sin(dot(${uv} + ${time} * 1.7, vec2(269.5, 183.3))) * 43758.5453);\n`,
      `    float ${id}_lr    = ${aperture} * sqrt(${id}_h1);\n`,
      `    float ${id}_lth   = 6.28318 * ${id}_h2;\n`,
      // When aperture=0, lr=0, so ro==ro0 and rd==rd0 (exact pinhole fallback, no branch needed)
      `    vec3  ${id}_ro    = ${id}_ro0 + ${id}_lr * (cos(${id}_lth) * ${id}_rgt + sin(${id}_lth) * ${id}_up2);\n`,
      `    vec3  ${id}_rd    = normalize((${id}_ro0 + ${id}_rd0 * ${focalDist}) - ${id}_ro);\n`,
    ].join('');

    return {
      code,
      outputVars: { ro: `${id}_ro`, rd: `${id}_rd` },
    };
  },
};

// ─── ForwardCameraNode ────────────────────────────────────────────────────────
// Fixed forward-facing pinhole camera — no orbit. ro = vec3(0,0,-camDist),
// rd = normalize(vec3(uv, fov)). Ideal for tunnel / fly-through scenes where
// the warp lives entirely in the march loop body.

export const ForwardCameraNode: NodeDefinition = {
  type: 'forwardCamera', label: 'Camera (Forward)', category: '3D Scene',
  description: 'Fixed forward-facing camera. ro sits at (0,0,−camDist) and rd = normalize(vec3(uv, fov)). No orbit — all motion lives inside the MLG body warp.',
  inputs: {
    uv:   { type: 'vec2',  label: 'UV' },
    time: { type: 'float', label: 'Time' },
  },
  outputs: {
    ro: { type: 'vec3', label: 'Ray Origin' },
    rd: { type: 'vec3', label: 'Ray Dir' },
  },
  defaultParams: { camDist: 3.0, fov: 1.0, aperture: 0.0, focalDist: 3.0 },
  paramDefs: {
    camDist:   { label: 'Cam Dist',   type: 'float' as const, min: 0.1, max: 20.0, step: 0.1 },
    fov:       { label: 'FOV',        type: 'float' as const, min: 0.3, max: 3.0,  step: 0.05 },
    aperture:  { label: 'Aperture',   type: 'float' as const, min: 0.0, max: 0.5,  step: 0.005, hint: 'Lens aperture radius. 0 = pinhole (no blur).' },
    focalDist: { label: 'Focal Dist', type: 'float' as const, min: 0.1, max: 50.0, step: 0.1,   hint: 'Distance from camera at which the scene is perfectly sharp.' },
  },
  generateGLSL: (node: GraphNode, inputVars) => {
    const id       = node.id;
    const uv       = inputVars.uv   || 'g_uv';
    const time     = inputVars.time || 'u_time';
    const d        = p(node.params.camDist,   3.0);
    const fov      = p(node.params.fov,       1.0);
    const aperture = p(node.params.aperture,  0.0);
    const focal    = p(node.params.focalDist, 3.0);
    return {
      code: [
        `    vec3  ${id}_ro0  = vec3(0.0, 0.0, -${d});\n`,
        `    vec3  ${id}_rd0  = normalize(vec3((${uv}).x, (${uv}).y, ${fov}));\n`,
        `    float ${id}_h1   = fract(sin(dot(${uv} + ${time}, vec2(127.1, 311.7))) * 43758.5453);\n`,
        `    float ${id}_h2   = fract(sin(dot(${uv} + ${time} * 1.7, vec2(269.5, 183.3))) * 43758.5453);\n`,
        `    float ${id}_lr   = ${aperture} * sqrt(${id}_h1);\n`,
        `    float ${id}_lth  = 6.28318 * ${id}_h2;\n`,
        `    vec3  ${id}_ro   = ${id}_ro0 + ${id}_lr * vec3(cos(${id}_lth), sin(${id}_lth), 0.0);\n`,
        `    vec3  ${id}_rd   = normalize((${id}_ro0 + ${id}_rd0 * ${focal}) - ${id}_ro);\n`,
      ].join(''),
      outputVars: { ro: `${id}_ro`, rd: `${id}_rd` },
    };
  },
};

// ─── MarchPosNode ─────────────────────────────────────────────────────────────
// Inside a marchLoopGroup, outputs the current ray march position (vec3).
// The compiler pre-registers this node's output as the `id_mp` function parameter.

export const MarchPosNode: NodeDefinition = {
  type: 'marchPos', label: 'March Pos', category: '3D Scene',
  deprecated: true,
  description: 'Inside a March Loop Group: outputs the current ray march position (vec3). Connect to SDF primitives and warp nodes.',
  inputs: {},
  outputs: { pos: { type: 'vec3', label: 'Position' } },
  defaultParams: {},
  paramDefs: {},
  generateGLSL: (node: GraphNode) => {
    const id = node.id;
    // Pre-registered by the compiler. Fallback for preview compilation.
    return {
      code: `    vec3 ${id}_pos = vec3(0.0);\n`,
      outputVars: { pos: `${id}_pos` },
    };
  },
};

// ─── MarchDistNode ────────────────────────────────────────────────────────────
// Inside a marchLoopGroup, outputs the current accumulated ray march distance.
// The compiler pre-registers this node's output as the `id_bt` function parameter.

export const MarchDistNode: NodeDefinition = {
  type: 'marchDist', label: 'March Dist', category: '3D Scene',
  deprecated: true,
  description: 'Inside a March Loop Group: outputs the current accumulated ray march distance (float). Wire into Twist3D or SpiralWarp3D angle input for depth-dependent effects.',
  inputs: {},
  outputs: { dist: { type: 'float', label: 'March Dist' } },
  defaultParams: {},
  paramDefs: {},
  generateGLSL: (node: GraphNode) => {
    const id = node.id;
    // Pre-registered by the compiler. Fallback for preview compilation.
    // Output key is 'dist'; GLSL var name is still id_t (the march accumulator).
    return {
      code: `    float ${id}_t = 0.0;\n`,
      outputVars: { dist: `${id}_t` },
    };
  },
};

// ─── SceneOutputNode ──────────────────────────────────────────────────────────
// Visual terminator inside a SceneGroup subgraph.  Wire the last SDF distance
// here to clearly show the chain end.  The SceneGroup compiler picks up the
// last float output in topological order, so this node also correctly marks
// the return value of the generated mapScene_<id> function.

export const SceneOutputNode: NodeDefinition = {
  type: 'sceneOutput', label: 'Scene Output', category: '3D Scene',
  description: 'Inside a Scene Group: marks the final SDF output. Connect the last SDF distance here — this becomes the return value of the scene function.',
  anchored: true,
  inputs:  { dist: { type: 'float', label: 'Distance' } },
  outputs: { dist: { type: 'float', label: 'Distance' } },
  defaultParams: {},
  paramDefs:    {},
  generateGLSL: (node: GraphNode, inputVars) => {
    const id   = node.id;
    const dist = inputVars.dist || '100.0';
    return {
      code: `    float ${id}_dist = ${dist};\n`,
      outputVars: { dist: `${id}_dist` },
    };
  },
};

// ─── MarchWarpOutputNode ──────────────────────────────────────────────────────
// Visual terminator inside a MarchLoopGroup warp subgraph.  Wire the final
// warped position here.  The MLG compiler picks up the last vec3 output in
// topological order, so this also correctly marks the warp function's return.

export const MarchWarpOutputNode: NodeDefinition = {
  type: 'marchOutput', label: 'Warp Output', category: '3D Scene',
  deprecated: true,
  description: 'Inside a March Loop Group subgraph: marks the final warped position. Connect the last vec3 from your warp chain here.',
  inputs:  { pos: { type: 'vec3', label: 'Position' } },
  outputs: { pos: { type: 'vec3', label: 'Position' } },
  defaultParams: {},
  paramDefs:    {},
  generateGLSL: (node: GraphNode, inputVars) => {
    const id  = node.id;
    const pos = inputVars.pos || 'vec3(0.0)';
    return {
      code: `    vec3 ${id}_pos = ${pos};\n`,
      outputVars: { pos: `${id}_pos` },
    };
  },
};

// ─── MarchLoopInputsNode ─────────────────────────────────────────────────────
export const MarchLoopInputsNode: NodeDefinition = {
  type: 'marchLoopInputs', label: 'Group Inputs', category: '3D Scene',
  description: 'Inside a March Loop Group: exposes ray origin/dir, march position/distance, and user-added inputs as output sockets.',
  anchored: true,
  inputs: {},
  outputs: {
    ro:        { type: 'vec3',  label: 'Ray Origin' },
    rd:        { type: 'vec3',  label: 'Ray Dir' },
    marchPos:  { type: 'vec3',  label: 'March Pos' },
    marchDist: { type: 'float', label: 'March Dist' },
  },
  defaultParams: { extraInputs: [] },
  paramDefs: {},
  generateGLSL: (node: GraphNode) => ({
    code: `    // marchLoopInputs ${node.id} — pre-registered by MLG compiler\n`,
    outputVars: {
      ro: `${node.id}_ro`, rd: `${node.id}_rd`,
      marchPos: `${node.id}_mp`, marchDist: `${node.id}_bt`,
    },
  }),
};

// ─── MarchLoopOutputNode ─────────────────────────────────────────────────────
export const MarchLoopOutputNode: NodeDefinition = {
  type: 'marchLoopOutput', label: 'Group Output', category: '3D Scene',
  description: 'Inside a March Loop Group: marks the warped position output. Toggle output port visibility with the eye icons.',
  anchored: true,
  inputs:  { pos: { type: 'vec3', label: 'Position' } },
  outputs: {},
  defaultParams: { hiddenOutputs: [] },
  paramDefs: {},
  generateGLSL: (node: GraphNode, inputVars) => {
    const pos = inputVars.pos || 'vec3(0.0)';
    return {
      code: `    vec3 ${node.id}_pos = ${pos};\n`,
      outputVars: { pos: `${node.id}_pos` },
    };
  },
};

// ─── MarchSceneDistNode ──────────────────────────────────────────────────────
// Inside a marchLoopGroup body, samples the scene SDF at the given position.
// The compiler replaces generateGLSL with a direct call to the scene function,
// exposing the per-step SDF distance so it can be accumulated (e.g. glow).

export const MarchSceneDistNode: NodeDefinition = {
  type: 'marchSceneDist', label: 'Scene Distance', category: '3D Scene',
  description: 'Inside a March Loop Group body: samples the scene SDF at the given position. Wire marchPos → here, then use the dist output with assignOp += to accumulate glow across march steps.',
  inputs: { pos: { type: 'vec3', label: 'Position' } },
  outputs: {
    dist:    { type: 'float', label: 'Distance' },
    rawDist: { type: 'float', label: 'Raw Distance (unclipped)' },
  },
  defaultParams: {},
  paramDefs: {},
  generateGLSL: (node: GraphNode, inputVars) => {
    const id  = node.id;
    const pos = inputVars.pos || 'vec3(0.0)';
    // Fallback for preview — the MLG compiler substitutes the real scene fn call
    return {
      code: `    float ${id}_d = length(${pos}) - 1.0;\n`,
      outputVars: { dist: `${id}_d`, rawDist: `${id}_d` },
    };
  },
};

// ─── MarchLoopGroupNode ────────────────────────────────────────────────────────
// A container node whose subgraph is compiled as a GLSL body-warp helper
// `vec3 marchBody_<slug>(vec3 <slug>_mp, float <slug>_bt)` called inside the
// ray march loop. Receives ro/rd from a MarchCamera and a scene3d SDF function.
// Double-click to enter the subgraph; MarchPos pre-populated inside.

export const MarchLoopGroupNode: NodeDefinition = {
  type: 'marchLoopGroup', label: 'March Loop Group', category: '3D Scene',
  description: 'Composable ray march loop. Connect MarchCamera (ro/rd), then double-click to build the loop body. Place a SceneGroup inside the body subgraph with MarchPos → [warps] → SceneGroup.pos. MarchDist gives the accumulated ray distance for depth-dependent effects.',
  inputs: {
    ro:    { type: 'vec3',    label: 'Ray Origin' },
    rd:    { type: 'vec3',    label: 'Ray Dir' },
    scene: { type: 'scene3d', label: 'Scene' },
    uv:    { type: 'vec2',    label: 'UV' },
    time:  { type: 'float',   label: 'Time' },
  },
  outputs: {
    color:     { type: 'vec3',  label: 'Color' },
    dist:      { type: 'float', label: 'Distance' },
    depth:     { type: 'float', label: 'Depth' },
    normal:    { type: 'vec3',  label: 'Normal' },
    iter:      { type: 'float', label: 'Iter' },
    iterCount: { type: 'float', label: 'Iter Count' },
    hit:       { type: 'float', label: 'Hit' },
    pos:       { type: 'vec3',  label: 'Hit Pos' },
  },
  defaultParams: {
    maxSteps: 80, maxDist: 20.0, stepScale: 1.0,
    volumetric: false, passthrough: 0.1, jitter: 0.0,
    bgR: 0.0, bgG: 0.0, bgB: 0.0,
    albedoR: 0.6, albedoG: 0.7, albedoB: 0.9,
  },
  paramDefs: {
    maxSteps:    { label: 'Max Steps',   type: 'float' as const,   min: 8,    max: 256,   step: 4,    hint: 'Maximum ray march iterations per pixel. Higher = deeper into geometry, more GPU cost.' },
    maxDist:     { label: 'Max Dist',    type: 'float' as const,   min: 5.0,  max: 100.0, step: 1.0,  hint: 'How far the ray travels before giving up and returning the background color.' },
    stepScale:   { label: 'Step Scale',  type: 'float' as const,   min: 0.3,  max: 1.0,   step: 0.05, hint: 'Fraction of the SDF distance to step each iteration. Lower = safer for thin features but slower. Not used in volumetric mode.' },
    volumetric:  { label: 'Volumetric',  type: 'bool'  as const,                                       hint: 'When on, the ray passes through the scene accumulating color at every step. No hit detection. Use with marchSceneDist + accumulator nodes in the body.' },
    passthrough: { label: 'Passthrough', type: 'float' as const,   min: 0.001, max: 0.5,  step: 0.005, hint: 'Minimum step size in volumetric mode. Prevents the ray from stalling at zero-distance surfaces. Also caps 1/vol to avoid blowout.' },
    jitter:      { label: 'Jitter',      type: 'float' as const,   min: 0.0,  max: 1.0,   step: 0.01,  hint: 'Randomise the first ray step by up to one step-width. Eliminates banding rings in volumetric mode. 0 = off.' },
    bgR:         { label: 'BG R',        type: 'float' as const,   min: 0.0,  max: 1.0,   step: 0.01, hint: 'Background color red channel — shown for rays that miss all geometry.' },
    bgG:         { label: 'BG G',        type: 'float' as const,   min: 0.0,  max: 1.0,   step: 0.01, hint: 'Background color green channel — shown for rays that miss all geometry.' },
    bgB:         { label: 'BG B',        type: 'float' as const,   min: 0.0,  max: 1.0,   step: 0.01, hint: 'Background color blue channel — shown for rays that miss all geometry.' },
    albedoR:     { label: 'Albedo R',    type: 'float' as const,   min: 0.0,  max: 1.0,   step: 0.01, hint: 'Default surface color red — used by the built-in diffuse shading (non-volumetric mode).' },
    albedoG:     { label: 'Albedo G',    type: 'float' as const,   min: 0.0,  max: 1.0,   step: 0.01, hint: 'Default surface color green — used by the built-in diffuse shading (non-volumetric mode).' },
    albedoB:     { label: 'Albedo B',    type: 'float' as const,   min: 0.0,  max: 1.0,   step: 0.01, hint: 'Default surface color blue — used by the built-in diffuse shading (non-volumetric mode).' },
  },
  // Stub — real code is generated by the compiler when it encounters type === 'marchLoopGroup'
  generateGLSL: () => ({ code: '', outputVars: {} }),
};

// ─── SpaceWarpGroupNode ────────────────────────────────────────────────────────
// A container node whose subgraph is compiled as a vec3→vec3 GLSL function.
// The compiler special-cases type === 'spaceWarpGroup' and emits a named function
// `vec3 warpSpace_<id>(vec3 p)` that is called inside the ray march loop before
// any SDF evaluation, enabling global coordinate field warping affecting all objects.

export const SpaceWarpGroupNode: NodeDefinition = {
  type: 'spaceWarpGroup', label: 'Space Warp Group', category: '3D Scene',
  description: 'Wrap vec3→vec3 warp nodes into a composable space warp. Connect ScenePos → warp chain → output. Wire the spacewarp3d output into RayMarch.',
  // Sockets are populated dynamically (same pattern as GroupNode / SceneGroupNode)
  inputs: {},
  outputs: { warp: { type: 'spacewarp3d', label: 'Warp' } },
  defaultParams: {},
  paramDefs: {},
  // Stub — real code is generated by the compiler when it encounters type === 'spaceWarpGroup'
  generateGLSL: () => ({ code: '', outputVars: {} }),
};

// ─── Shared camera + march GLSL emitter ───────────────────────────────────────
// Returns the shared code string for camera setup + ray march + normal estimation.
// Used by both RayMarchNode and RayMarchLitNode.

function emitSharedMarchCode(
  id: string,
  uv: string,
  time: string,
  sceneFn: string,
  camDist: string,
  camAngle: string,
  rotSpeed: string,
  fov: string,
  maxSteps: number,
  maxDist: string,
  warpFn?: string,
): string {
  // Identity when no warpFn; applies space warp when provided.
  // Epsilon samples go through warp(raw + eps) so normals are correct in warp-space.
  const warp = (expr: string) => warpFn ? `${warpFn}(${expr})` : expr;
  return [
    `    float ${id}_ang = ${camAngle} + ${time} * ${rotSpeed};\n`,
    // Camera height scales with distance (≈30%) so the elevation angle stays constant.
    // This prevents the "tipping down" effect at low camDist values where a fixed
    // height (0.8) would dominate and produce a near-vertical look direction,
    // eventually collapsing the right-vector via cross(worldUp, fwd) → zero.
    `    float ${id}_ch  = max(${camDist} * 0.3, 0.15);\n`,
    `    vec3  ${id}_ro  = vec3(sin(${id}_ang)*${camDist}, ${id}_ch, cos(${id}_ang)*${camDist});\n`,
    `    vec3  ${id}_ta  = vec3(0.0);\n`,
    `    vec3  ${id}_fwd = normalize(${id}_ta - ${id}_ro);\n`,
    `    vec3  ${id}_rgt = normalize(cross(vec3(0.0,1.0,0.0), ${id}_fwd));\n`,
    `    vec3  ${id}_up2 = cross(${id}_fwd, ${id}_rgt);\n`,
    `    vec3  ${id}_rd  = normalize(${uv}.x * ${id}_rgt + ${uv}.y * ${id}_up2 + ${fov} * ${id}_fwd);\n`,
    `    float ${id}_t   = 0.001;\n`,
    `    float ${id}_hit = 0.0;\n`,
    `    int   ${id}_si  = 0;\n`,
    `    for (int ${id}_i = 0; ${id}_i < ${maxSteps}; ${id}_i++) {\n`,
    `        vec3  ${id}_rp_raw = ${id}_ro + ${id}_t * ${id}_rd;\n`,
    `        vec3  ${id}_rp = ${warp(`${id}_rp_raw`)};\n`,
    `        float ${id}_d  = ${sceneFn}(${id}_rp);\n`,
    `        if (${id}_d < 0.0005) { ${id}_hit = 1.0; ${id}_si = ${id}_i; break; }\n`,
    `        ${id}_t += ${id}_d;\n`,
    `        if (${id}_t > ${maxDist}) { ${id}_si = ${id}_i; break; }\n`,
    `    }\n`,
    `    float ${id}_iter      = float(${id}_si) / float(${maxSteps});\n`,
    `    float ${id}_iterCount = float(${id}_si);\n`,
    `    vec3  ${id}_hp_raw  = ${id}_ro + ${id}_t * ${id}_rd;\n`,
    `    vec3  ${id}_hp  = ${warp(`${id}_hp_raw`)};\n`,
    `    float ${id}_e   = 0.001;\n`,
    // Normal estimation: perturb the RAW (Euclidean) position, apply warp, then call SDF.
    // This computes the gradient of (sceneFn ∘ warpFn) w.r.t. world-space position.
    `    vec3  ${id}_n   = normalize(vec3(\n`,
    `        ${sceneFn}(${warp(`${id}_hp_raw+vec3(${id}_e,0.0,0.0)`)}) - ${sceneFn}(${warp(`${id}_hp_raw-vec3(${id}_e,0.0,0.0)`)}),\n`,
    `        ${sceneFn}(${warp(`${id}_hp_raw+vec3(0.0,${id}_e,0.0)`)}) - ${sceneFn}(${warp(`${id}_hp_raw-vec3(0.0,${id}_e,0.0)`)}),\n`,
    `        ${sceneFn}(${warp(`${id}_hp_raw+vec3(0.0,0.0,${id}_e)`)}) - ${sceneFn}(${warp(`${id}_hp_raw-vec3(0.0,0.0,${id}_e)`)})\n`,
    `    ));\n`,
    `    float ${id}_dist   = ${id}_t;\n`,
    // Depth: raw camera-to-hit distance normalised by maxDist.
    // Background pixels naturally reach t≈maxDist so depth→1 without special casing.
    `    float ${id}_depth  = clamp(${id}_t / ${maxDist}, 0.0, 1.0);\n`,
    `    vec3  ${id}_normal = ${id}_n * ${id}_hit;\n`,
  ].join('');
}

// ─── Common paramDefs shared by both march nodes ──────────────────────────────

const COMMON_MARCH_PARAM_DEFS = {
  camDist:   { label: 'Cam Dist',  type: 'float' as const, min: 0.5, max: 20.0,  step: 0.05 },
  camAngle:  { label: 'Cam Angle', type: 'float' as const, min: 0.0, max: 6.28,  step: 0.02 },
  rotSpeed:  { label: 'Rot Speed', type: 'float' as const, min: 0.0, max: 2.0,   step: 0.01 },
  fov:       { label: 'FOV',       type: 'float' as const, min: 0.5, max: 3.14,  step: 0.05 },
  maxSteps:  { label: 'Max Steps', type: 'float' as const, min: 8,   max: 256,   step: 4    },
  maxDist:   { label: 'Max Dist',  type: 'float' as const, min: 5.0, max: 100.0, step: 1.0  },
};

// ─── RayMarchNode ──────────────────────────────────────────────────────────────
// Camera + march only. No color computation.
// Outputs raw data: dist, depth, normal, iter, hit.

export const RayMarchNode: NodeDefinition = {
  type: 'rayMarch', label: 'Ray March', category: '3D Scene',
  description: 'Camera + sphere-march. Outputs raw hit data (dist, depth, normal, iter, hit) — no color. Connect to palette/math nodes for custom coloring. Wire a SpaceWarpGroup to spacewarp to bend the entire scene coordinate field inside the march loop.',
  inputs: {
    scene:     { type: 'scene3d',     label: 'Scene' },
    spacewarp: { type: 'spacewarp3d', label: 'Space Warp' },
    uv:       { type: 'vec2',   label: 'UV' },
    time:     { type: 'float',  label: 'Time' },
    camDist:  { type: 'float',  label: 'Cam Distance' },
    camAngle: { type: 'float',  label: 'Cam Angle' },
    rotSpeed: { type: 'float',  label: 'Rot Speed' },
    fov:      { type: 'float',  label: 'FOV' },
    maxDist:  { type: 'float',  label: 'Max Dist' },
  },
  outputs: {
    color:     { type: 'vec3',  label: 'Color' },
    dist:      { type: 'float', label: 'Distance' },
    depth:     { type: 'float', label: 'Depth' },
    normal:    { type: 'vec3',  label: 'Normal' },
    iter:      { type: 'float', label: 'Iter' },
    iterCount: { type: 'float', label: 'Iter Count' },
    hit:       { type: 'float', label: 'Hit' },
    pos:       { type: 'vec3',  label: 'Hit Pos' },
  },
  defaultParams: {
    camDist: 3.0, camAngle: 0.6, rotSpeed: 0.0, fov: 1.5, maxSteps: 64, maxDist: 20.0,
    bgR: 0.85, bgG: 0.90, bgB: 0.95,
  },
  paramDefs: {
    ...COMMON_MARCH_PARAM_DEFS,
    bgR: { label: 'BG R', type: 'float' as const, min: 0.0, max: 1.0, step: 0.01 },
    bgG: { label: 'BG G', type: 'float' as const, min: 0.0, max: 1.0, step: 0.01 },
    bgB: { label: 'BG B', type: 'float' as const, min: 0.0, max: 1.0, step: 0.01 },
  },
  generateGLSL: (node: GraphNode, inputVars) => {
    const id       = node.id;
    const uv       = inputVars.uv       || 'g_uv';
    const time     = inputVars.time     || 'u_time';
    const sceneFn  = inputVars.scene    || 'MISSING_SCENE_FN';
    const warpFn   = inputVars.spacewarp || undefined;
    const camDist  = inputVars.camDist  || p(node.params.camDist,  3.0);
    const camAngle = inputVars.camAngle || p(node.params.camAngle, 0.6);
    const rotSpeed = inputVars.rotSpeed || p(node.params.rotSpeed, 0.0);
    const fov      = inputVars.fov      || p(node.params.fov,      1.5);
    const maxSteps = Math.max(16, Math.min(256, Number(node.params.maxSteps) || 64));
    const maxDist  = inputVars.maxDist   || p(node.params.maxDist,  20.0);

    const code = emitSharedMarchCode(id, uv, time, sceneFn, camDist, camAngle, rotSpeed, fov, maxSteps, maxDist, warpFn);

    const bgr = p(node.params.bgR, 0.85);
    const bgg = p(node.params.bgG, 0.90);
    const bgb = p(node.params.bgB, 0.95);
    const colorCode = [
      `    vec3  ${id}_bg    = vec3(${bgr}, ${bgg}, ${bgb});\n`,
      `    vec3  ${id}_color = ${id}_hit > 0.5 ? (${id}_normal * 0.5 + 0.5) : ${id}_bg;\n`,
    ].join('');

    return {
      code: code + colorCode,
      outputVars: {
        color:     `${id}_color`,
        dist:      `${id}_dist`,
        depth:     `${id}_depth`,
        normal:    `${id}_normal`,
        iter:      `${id}_iter`,
        iterCount: `${id}_iterCount`,
        hit:       `${id}_hit`,
        pos:       `${id}_hp`,
      },
    };
  },
};

// ─── RayRenderNode ─────────────────────────────────────────────────────────────
// LEGACY — kept for backward compatibility with saved graphs.
// New graphs should use RayMarchNode instead.

export const RayRenderNode: NodeDefinition = {
  type: 'rayRender', label: 'Ray Render (Legacy)', category: '3D Scene',
  description: 'Legacy sphere-tracer. Use RayMarch or RayMarchLit for new graphs.',
  inputs: {
    scene:     { type: 'scene3d', label: 'Scene' },
    uv:        { type: 'vec2',  label: 'UV' },
    time:      { type: 'float', label: 'Time' },
    camDist:   { type: 'float', label: 'Cam Distance' },
    fov:       { type: 'float', label: 'FOV' },
    cam_rot_h: { type: 'float', label: 'Cam Rot H' },
    cam_rot_v: { type: 'float', label: 'Cam Rot V' },
  },
  outputs: {
    color:  { type: 'vec3',  label: 'Color' },
    depth:  { type: 'float', label: 'Depth' },
    normal: { type: 'vec3',  label: 'Normal' },
    iter:   { type: 'float', label: 'Iter Count' },
  },
  defaultParams: {
    color_mode:  'lit',
    camDist:     3.0,
    camAngle:    0.6,
    camRotSpeed: 0.0,
    fov:         1.5,
    maxSteps:    64,
    maxDist:     20.0,
    dist_scale:  0.04,
    iter_scale:  0.005,
    pal_r:       0.0,
    pal_g:       0.33,
    pal_b:       0.67,
    bgR: 0.85, bgG: 0.90, bgB: 0.95,
    shadow_soft:  'on',
    ao_strength:  1.0,
    lightX:     1.0,
    lightY:     2.0,
    lightZ:     3.0,
    albedoR: 0.6, albedoG: 0.65, albedoB: 0.7,
  },
  paramDefs: {
    color_mode: { label: 'Color Mode', type: 'select', options: [
      { value: 'lit',      label: 'Lit (PBR)'           },
      { value: 'distance', label: 'Distance (Kishimisu)' },
      { value: 'normal',   label: 'Normals'              },
      { value: 'iter',     label: 'Iter Count'           },
    ]},
    camDist:     { label: 'Cam Dist',    type: 'float', min: 0.5, max: 20.0, step: 0.05 },
    camAngle:    { label: 'Cam Angle',   type: 'float', min: 0.0, max: 6.28,  step: 0.02 },
    camRotSpeed: { label: 'Rot Speed',   type: 'float', min: 0.0, max: 2.0,   step: 0.01 },
    fov:         { label: 'FOV',         type: 'float', min: 0.5, max: 3.14,  step: 0.05 },
    maxSteps: { label: 'Max Steps', type: 'select', options: [32,64,96,128].map(n => ({ value: String(n), label: String(n) })) },
    maxDist:  { label: 'Max Dist',  type: 'float', min: 5.0, max: 100.0, step: 1.0 },
    dist_scale:  { label: 'Dist Scale',  type: 'float', min: 0.0, max: 0.3,  step: 0.001 },
    iter_scale:  { label: 'Iter Scale',  type: 'float', min: 0.0, max: 0.05, step: 0.0005 },
    pal_r:       { label: 'Palette R',   type: 'float', min: 0.0, max: 1.0,  step: 0.01 },
    pal_g:       { label: 'Palette G',   type: 'float', min: 0.0, max: 1.0,  step: 0.01 },
    pal_b:       { label: 'Palette B',   type: 'float', min: 0.0, max: 1.0,  step: 0.01 },
    bgR:      { label: 'BG R',      type: 'float', min: 0.0, max: 1.0, step: 0.01 },
    bgG:      { label: 'BG G',      type: 'float', min: 0.0, max: 1.0, step: 0.01 },
    bgB:      { label: 'BG B',      type: 'float', min: 0.0, max: 1.0, step: 0.01 },
    shadow_soft: { label: 'Soft Shadows', type: 'select', options: [{ value: 'on', label: 'On' }, { value: 'off', label: 'Off' }] },
    ao_strength: { label: 'AO Strength', type: 'float', min: 0.0, max: 2.0, step: 0.05 },
    lightX:   { label: 'Light X',   type: 'float', min: -10.0, max: 10.0, step: 0.1 },
    lightY:   { label: 'Light Y',   type: 'float', min: -10.0, max: 10.0, step: 0.1 },
    lightZ:   { label: 'Light Z',   type: 'float', min: -10.0, max: 10.0, step: 0.1 },
    albedoR:  { label: 'Albedo R',  type: 'float', min: 0.0, max: 1.0, step: 0.01 },
    albedoG:  { label: 'Albedo G',  type: 'float', min: 0.0, max: 1.0, step: 0.01 },
    albedoB:  { label: 'Albedo B',  type: 'float', min: 0.0, max: 1.0, step: 0.01 },
  },
  generateGLSL: (node: GraphNode, inputVars) => {
    const id       = node.id;
    const uv       = inputVars.uv      || 'g_uv';
    const time     = inputVars.time    || 'u_time';
    const sceneFn  = inputVars.scene   || 'MISSING_SCENE_FN';
    const camDist  = inputVars.camDist || p(node.params.camDist, 3.0);
    const camAngle = p(node.params.camAngle, 0.6);
    const rotSpeed = p(node.params.camRotSpeed, 0.0);
    const fov      = inputVars.fov     || p(node.params.fov, 1.5);
    const maxSteps = Math.max(16, Math.min(256, Number(node.params.maxSteps) || 64));
    const maxDist  = p(node.params.maxDist, 20.0);
    const lx = p(node.params.lightX, 1.0);
    const ly = p(node.params.lightY, 2.0);
    const lz = p(node.params.lightZ, 3.0);
    const bgr = p(node.params.bgR, 0.85);
    const bgg = p(node.params.bgG, 0.90);
    const bgb = p(node.params.bgB, 0.95);
    const ar = p(node.params.albedoR, 0.6);
    const ag = p(node.params.albedoG, 0.65);
    const ab = p(node.params.albedoB, 0.7);
    const cam_rot_h = inputVars.cam_rot_h || '0.0';
    const cam_rot_v = inputVars.cam_rot_v || '0.0';
    const aoStr     = p(node.params.ao_strength, 1.0);
    const shadowSoft = (node.params.shadow_soft as string) ?? 'on';
    const colorMode  = (node.params.color_mode as string) ?? 'lit';
    const distScale  = p(node.params.dist_scale, 0.04);
    const iterScale  = p(node.params.iter_scale, 0.005);
    const palR       = p(node.params.pal_r, 0.0);
    const palG       = p(node.params.pal_g, 0.33);
    const palB       = p(node.params.pal_b, 0.67);

    // Shared: camera + ray march + normal — always emitted
    const sharedCode = [
      // Camera setup — angle is static + optional rotation speed
      `    float ${id}_ang = ${camAngle} + ${time} * ${rotSpeed};\n`,
      `    vec3  ${id}_ro  = vec3(sin(${id}_ang)*${camDist}, 0.8, cos(${id}_ang)*${camDist});\n`,
      `    vec3  ${id}_ta  = vec3(0.0);\n`,
      `    vec3  ${id}_fwd = normalize(${id}_ta - ${id}_ro);\n`,
      `    vec3  ${id}_rgt = normalize(cross(vec3(0.0,1.0,0.0), ${id}_fwd));\n`,
      `    vec3  ${id}_up2 = cross(${id}_fwd, ${id}_rgt);\n`,
      `    vec3  ${id}_rd  = normalize(${uv}.x * ${id}_rgt + ${uv}.y * ${id}_up2 + ${fov} * ${id}_fwd);\n`,
      // Apply horizontal rotation around Y (cam_rot_h) and vertical tilt (cam_rot_v)
      `    float ${id}_crh = ${cam_rot_h};\n`,
      `    float ${id}_crv = ${cam_rot_v};\n`,
      `    vec3  ${id}_rd2 = ${id}_rd;\n`,
      `    ${id}_rd2.xz = vec2(cos(${id}_crh)*${id}_rd.x + sin(${id}_crh)*${id}_rd.z, -sin(${id}_crh)*${id}_rd.x + cos(${id}_crh)*${id}_rd.z);\n`,
      `    ${id}_rd2.yz = vec2(cos(${id}_crv)*${id}_rd2.y - sin(${id}_crv)*${id}_rd2.z, sin(${id}_crv)*${id}_rd2.y + cos(${id}_crv)*${id}_rd2.z);\n`,
      `    ${id}_rd = ${id}_rd2;\n`,
      // Ray march — track step count for iter output
      `    float ${id}_t   = 0.001;\n`,
      `    float ${id}_hit = 0.0;\n`,
      `    int   ${id}_si  = 0;\n`,
      `    for (int ${id}_i = 0; ${id}_i < ${maxSteps}; ${id}_i++) {\n`,
      `        vec3  ${id}_rp = ${id}_ro + ${id}_t * ${id}_rd;\n`,
      `        float ${id}_d  = ${sceneFn}(${id}_rp);\n`,
      `        if (${id}_d < 0.0005) { ${id}_hit = 1.0; ${id}_si = ${id}_i; break; }\n`,
      `        ${id}_t += ${id}_d;\n`,
      `        if (${id}_t > ${maxDist}) { ${id}_si = ${id}_i; break; }\n`,
      `    }\n`,
      `    float ${id}_iter = float(${id}_si) / float(${maxSteps});\n`,
      // Normal estimation
      `    vec3  ${id}_hp  = ${id}_ro + ${id}_t * ${id}_rd;\n`,
      `    float ${id}_e   = 0.001;\n`,
      `    vec3  ${id}_n   = normalize(vec3(\n`,
      `        ${sceneFn}(${id}_hp+vec3(${id}_e,0.0,0.0)) - ${sceneFn}(${id}_hp-vec3(${id}_e,0.0,0.0)),\n`,
      `        ${sceneFn}(${id}_hp+vec3(0.0,${id}_e,0.0)) - ${sceneFn}(${id}_hp-vec3(0.0,${id}_e,0.0)),\n`,
      `        ${sceneFn}(${id}_hp+vec3(0.0,0.0,${id}_e)) - ${sceneFn}(${id}_hp-vec3(0.0,0.0,${id}_e))\n`,
      `    ));\n`,
      `    vec3  ${id}_bg  = vec3(${bgr}, ${bgg}, ${bgb});\n`,
    ].join('');

    // Mode-specific coloring code
    let coloringCode: string;

    if (colorMode === 'distance') {
      coloringCode = [
        // Kishimisu palette coloring: distance + iter count drives hue
        `    float ${id}_pal_t = ${id}_t * ${distScale} + ${id}_iter * ${iterScale};\n`,
        `    vec3  ${id}_pal_c = vec3(${palR}, ${palG}, ${palB});\n`,
        `    vec3  ${id}_lit   = 0.5 + 0.5 * cos(6.28318 * (vec3(${id}_pal_t) + ${id}_pal_c));\n`,
        `    vec3  ${id}_color = mix(${id}_lit, ${id}_bg, 1.0 - ${id}_hit);\n`,
      ].join('');
    } else if (colorMode === 'normal') {
      coloringCode = [
        `    vec3  ${id}_lit   = ${id}_n * 0.5 + 0.5;\n`,
        `    vec3  ${id}_color = mix(${id}_lit, ${id}_bg, 1.0 - ${id}_hit);\n`,
      ].join('');
    } else if (colorMode === 'iter') {
      coloringCode = [
        `    vec3  ${id}_lit   = vec3(${id}_iter);\n`,
        `    vec3  ${id}_color = mix(${id}_lit, ${id}_bg, 1.0 - ${id}_hit);\n`,
      ].join('');
    } else {
      // 'lit' — full PBR lighting with shadow + AO
      coloringCode = [
        // Lighting — key light direction
        `    vec3  ${id}_ld  = normalize(vec3(${lx}, ${ly}, ${lz}));\n`,
        `    float ${id}_dif = clamp(dot(${id}_n, ${id}_ld), 0.0, 1.0);\n`,
        // Sky-dome ambient: brighter hemisphere
        `    float ${id}_amb = 0.4 + 0.6 * (${id}_n.y * 0.5 + 0.5);\n`,
        // Soft shadows (penumbra ray march toward light)
        ...(shadowSoft === 'on' ? [
          `    float ${id}_sha = 1.0;\n`,
          `    vec3  ${id}_sro = ${id}_hp + ${id}_n * 0.002;\n`,
          `    float ${id}_st  = 0.01;\n`,
          `    for (int ${id}_si2 = 0; ${id}_si2 < 24; ${id}_si2++) {\n`,
          `        float ${id}_sd = ${sceneFn}(${id}_sro + ${id}_ld * ${id}_st);\n`,
          `        if (${id}_sd < 0.0001) { ${id}_sha = 0.0; break; }\n`,
          `        ${id}_sha = min(${id}_sha, 8.0 * ${id}_sd / ${id}_st);\n`,
          `        ${id}_st += ${id}_sd;\n`,
          `        if (${id}_st > 5.0) break;\n`,
          `    }\n`,
          `    ${id}_sha = clamp(${id}_sha, 0.0, 1.0);\n`,
          `    ${id}_dif *= ${id}_sha;\n`,
        ] : []),
        // Ambient occlusion (5-step march along normal)
        `    float ${id}_ao = 0.0;\n`,
        `    float ${id}_ao_scale = 1.0;\n`,
        `    for (int ${id}_aoi = 1; ${id}_aoi < 6; ${id}_aoi++) {\n`,
        `        float ${id}_ao_d = float(${id}_aoi) * 0.08;\n`,
        `        float ${id}_ao_s = ${id}_ao_d - ${sceneFn}(${id}_hp + ${id}_n * ${id}_ao_d);\n`,
        `        ${id}_ao += ${id}_ao_s * ${id}_ao_scale;\n`,
        `        ${id}_ao_scale *= 0.5;\n`,
        `    }\n`,
        `    ${id}_ao = clamp(1.0 - 3.0 * ${id}_ao, 0.0, 1.0);\n`,
        // Blend AO by strength parameter (0 = no AO, 1+ = full)
        `    float ${id}_ao_f = mix(1.0, ${id}_ao, clamp(${aoStr}, 0.0, 2.0));\n`,
        `    ${id}_dif *= ${id}_ao_f;\n`,
        `    ${id}_amb *= ${id}_ao_f;\n`,
        // Final shading — warm key light + subtle sky colour
        `    vec3  ${id}_alb = vec3(${ar}, ${ag}, ${ab});\n`,
        `    vec3  ${id}_sky = vec3(0.5, 0.7, 1.0) * ${id}_amb * 0.6;\n`,
        `    vec3  ${id}_lit = ${id}_alb * (${id}_dif * vec3(1.0, 0.9, 0.8) + ${id}_sky + ${id}_amb * 0.2);\n`,
        // Fog / background blend — subtract camera distance so scene objects don't
        // inherit the camera-to-scene ray length, which would wash out silhouette edges.
        `    float ${id}_fog = clamp((${id}_t - length(${id}_ro)) / ${maxDist}, 0.0, 1.0);\n`,
        `    vec3  ${id}_color = mix(mix(${id}_lit, ${id}_bg, ${id}_fog), ${id}_bg, 1.0 - ${id}_hit);\n`,
      ].join('');
    }

    const finalCode = [
      `    float ${id}_depth = clamp(${id}_t / ${maxDist}, 0.0, 1.0);\n`,
      `    vec3  ${id}_normal = ${id}_n * ${id}_hit;\n`,
    ].join('');

    return {
      code: sharedCode + coloringCode + finalCode,
      outputVars: {
        color:  `${id}_color`,
        depth:  `${id}_depth`,
        normal: `${id}_normal`,
        iter:   `${id}_iter`,
      },
    };
  },
};
