/**
 * scene3d.ts — Composable 3D scene system (Phase 3, V2)
 *
 * Three nodes work together:
 *
 *  ScenePosNode  — outputs the ray position `p` (vec3) inside a scene function.
 *  SceneGroupNode — a group-like container whose subgraph is compiled as a named
 *                   GLSL function `float mapScene_<id>(vec3 p)`.  Its output is
 *                   of type `scene3d` — just the function name string on the wire.
 *  RayRenderNode  — a full sphere-tracer that calls the `scene3d` function.
 *                   Outputs: color (vec3), depth (float).
 *
 * Compiler contract (shaderAssembler.ts):
 *   - When a node of type 'sceneGroup' is encountered, its subgraph is compiled
 *     into a standalone GLSL function and added to the functions set.
 *   - ScenePosNode inside a sceneGroup outputs the literal string 'p' (the func arg).
 *   - The sceneGroup's `scene3d` output var is the function name, e.g. `mapScene_<id>`.
 *   - RayRenderNode receives this as its `scene` inputVar and plugs it into the march loop.
 */
import type { NodeDefinition, GraphNode } from '../../types/nodeGraph';
import { p } from './helpers';

// ─── ScenePosNode ──────────────────────────────────────────────────────────────
// Inside a sceneGroup, outputs the ray march position `p` (the function parameter).
// The compiler replaces its output var with the literal string 'p' when inside
// a sceneGroup compilation context.  See shaderAssembler.ts sceneGroup handler.

export const ScenePosNode: NodeDefinition = {
  type: 'scenePos', label: 'Scene Pos', category: '3D Scene',
  description: 'Inside a Scene Group: outputs the current ray march position (vec3 p). Connect to SDF primitive inputs.',
  inputs: {},
  outputs: { pos: { type: 'vec3', label: 'Position' } },
  defaultParams: {},
  paramDefs: {},
  generateGLSL: (node: GraphNode) => {
    const id = node.id;
    // In a sceneGroup context the compiler pre-registers this node's output as 'p'.
    // This fallback is used when the node is compiled outside a sceneGroup (preview etc.).
    return {
      code: `    vec3 ${id}_pos = vec3(0.0);\n`,
      outputVars: { pos: `${id}_pos` },
    };
  },
};

// ─── SceneGroupNode ────────────────────────────────────────────────────────────
// A container node (like GroupNode) whose subgraph is compiled as a GLSL function.
// The compiler special-cases type === 'sceneGroup' exactly like type === 'group',
// but emits a named function instead of inlining code.

export const SceneGroupNode: NodeDefinition = {
  type: 'sceneGroup', label: 'Scene Group', category: '3D Scene',
  description: 'Wrap SDF nodes into a composable 3D scene. Connect ScenePos → SDF chain → output. Wire the scene3d output into RayRender.',
  // Sockets are populated dynamically (same pattern as GroupNode)
  inputs: {},
  outputs: { scene: { type: 'scene3d', label: 'Scene' } },
  defaultParams: {},
  paramDefs: {},
  // Stub — real code is generated by the compiler when it encounters type === 'sceneGroup'
  generateGLSL: () => ({ code: '', outputVars: {} }),
};

// ─── RayRenderNode ─────────────────────────────────────────────────────────────
// Full sphere-tracer that calls a `scene3d` function (mapScene_<id>).
// The `scene` input is a scene3d wire carrying the function name string.

const RAY_RENDER_GLSL = `
vec3 rayRenderNormal(float(*sdf)(vec3), vec3 p) {
    float eps = 0.001;
    return normalize(vec3(
        sdf(vec3(p.x+eps,p.y,p.z)) - sdf(vec3(p.x-eps,p.y,p.z)),
        sdf(vec3(p.x,p.y+eps,p.z)) - sdf(vec3(p.x,p.y-eps,p.z)),
        sdf(vec3(p.x,p.y,p.z+eps)) - sdf(vec3(p.x,p.y,p.z-eps))
    ));
}`;
// Note: function pointers aren't in GLSL ES 1.00. RayRenderNode embeds the scene call inline.

export const RayRenderNode: NodeDefinition = {
  type: 'rayRender', label: 'Ray Render', category: '3D Scene',
  description: 'Full sphere-tracer. Connect a Scene Group to the Scene input. Outputs shaded color and raw depth.',
  inputs: {
    scene:     { type: 'scene3d', label: 'Scene' },
    uv:        { type: 'vec2',  label: 'UV' },
    time:      { type: 'float', label: 'Time' },
    camDist:   { type: 'float', label: 'Cam Distance' },
    fov:       { type: 'float', label: 'FOV' },
    cam_rot_h: { type: 'float', label: 'Cam Rot H' },
    cam_rot_v: { type: 'float', label: 'Cam Rot V' },
  },
  outputs: {
    color:  { type: 'vec3',  label: 'Color' },
    depth:  { type: 'float', label: 'Depth' },
    normal: { type: 'vec3',  label: 'Normal' },
    iter:   { type: 'float', label: 'Iter Count' },
  },
  defaultParams: {
    camDist:    3.0,
    camAngle:   0.6,
    camRotSpeed: 0.0,
    fov:        1.5,
    maxSteps:   64,
    maxDist:    20.0,
    lightX:     1.0,
    lightY:     2.0,
    lightZ:     3.0,
    bgR: 0.05, bgG: 0.05, bgB: 0.08,
    albedoR: 0.6, albedoG: 0.7, albedoB: 0.9,
  },
  paramDefs: {
    camDist:     { label: 'Cam Dist',    type: 'float', min: 0.5, max: 20.0, step: 0.05 },
    camAngle:    { label: 'Cam Angle',   type: 'float', min: 0.0, max: 6.28,  step: 0.02 },
    camRotSpeed: { label: 'Rot Speed',   type: 'float', min: 0.0, max: 2.0,   step: 0.01 },
    fov:         { label: 'FOV',         type: 'float', min: 0.5, max: 3.14,  step: 0.05 },
    maxSteps: { label: 'Max Steps', type: 'select', options: [32,64,96,128].map(n => ({ value: String(n), label: String(n) })) },
    maxDist:  { label: 'Max Dist',  type: 'float', min: 5.0, max: 100.0, step: 1.0 },
    lightX:   { label: 'Light X',   type: 'float', min: -10.0, max: 10.0, step: 0.1 },
    lightY:   { label: 'Light Y',   type: 'float', min: -10.0, max: 10.0, step: 0.1 },
    lightZ:   { label: 'Light Z',   type: 'float', min: -10.0, max: 10.0, step: 0.1 },
    bgR:      { label: 'BG R',      type: 'float', min: 0.0, max: 1.0, step: 0.01 },
    bgG:      { label: 'BG G',      type: 'float', min: 0.0, max: 1.0, step: 0.01 },
    bgB:      { label: 'BG B',      type: 'float', min: 0.0, max: 1.0, step: 0.01 },
    albedoR:  { label: 'Albedo R',  type: 'float', min: 0.0, max: 1.0, step: 0.01 },
    albedoG:  { label: 'Albedo G',  type: 'float', min: 0.0, max: 1.0, step: 0.01 },
    albedoB:  { label: 'Albedo B',  type: 'float', min: 0.0, max: 1.0, step: 0.01 },
  },
  generateGLSL: (node: GraphNode, inputVars) => {
    const id       = node.id;
    const uv       = inputVars.uv      || 'g_uv';
    const time     = inputVars.time    || 'u_time';
    const sceneFn  = inputVars.scene   || 'MISSING_SCENE_FN';
    const camDist  = inputVars.camDist || p(node.params.camDist, 3.0);
    const camAngle = p(node.params.camAngle, 0.6);
    const rotSpeed = p(node.params.camRotSpeed, 0.0);
    const fov      = inputVars.fov     || p(node.params.fov, 1.5);
    const maxSteps = Math.max(16, Math.min(256, Number(node.params.maxSteps) || 64));
    const maxDist  = p(node.params.maxDist, 20.0);
    const lx = p(node.params.lightX, 1.0);
    const ly = p(node.params.lightY, 2.0);
    const lz = p(node.params.lightZ, 3.0);
    const bgr = p(node.params.bgR, 0.05);
    const bgg = p(node.params.bgG, 0.05);
    const bgb = p(node.params.bgB, 0.08);
    const ar = p(node.params.albedoR, 0.6);
    const ag = p(node.params.albedoG, 0.7);
    const ab = p(node.params.albedoB, 0.9);
    const cam_rot_h = inputVars.cam_rot_h || '0.0';
    const cam_rot_v = inputVars.cam_rot_v || '0.0';

    return {
      code: [
        // Camera setup — angle is static + optional rotation speed
        `    float ${id}_ang = ${camAngle} + ${time} * ${rotSpeed};\n`,
        `    vec3  ${id}_ro  = vec3(sin(${id}_ang)*${camDist}, 0.8, cos(${id}_ang)*${camDist});\n`,
        `    vec3  ${id}_ta  = vec3(0.0);\n`,
        `    vec3  ${id}_fwd = normalize(${id}_ta - ${id}_ro);\n`,
        `    vec3  ${id}_rgt = normalize(cross(vec3(0.0,1.0,0.0), ${id}_fwd));\n`,
        `    vec3  ${id}_up2 = cross(${id}_fwd, ${id}_rgt);\n`,
        `    vec3  ${id}_rd  = normalize(${uv}.x * ${id}_rgt + ${uv}.y * ${id}_up2 + ${fov} * ${id}_fwd);\n`,
        // Apply horizontal rotation around Y (cam_rot_h) and vertical tilt (cam_rot_v)
        `    float ${id}_crh = ${cam_rot_h};\n`,
        `    float ${id}_crv = ${cam_rot_v};\n`,
        `    vec3  ${id}_rd2 = ${id}_rd;\n`,
        `    ${id}_rd2.xz = vec2(cos(${id}_crh)*${id}_rd.x + sin(${id}_crh)*${id}_rd.z, -sin(${id}_crh)*${id}_rd.x + cos(${id}_crh)*${id}_rd.z);\n`,
        `    ${id}_rd2.yz = vec2(cos(${id}_crv)*${id}_rd2.y - sin(${id}_crv)*${id}_rd2.z, sin(${id}_crv)*${id}_rd2.y + cos(${id}_crv)*${id}_rd2.z);\n`,
        `    ${id}_rd = ${id}_rd2;\n`,
        // Ray march — track step count for iter output
        `    float ${id}_t   = 0.001;\n`,
        `    float ${id}_hit = 0.0;\n`,
        `    int   ${id}_si  = 0;\n`,
        `    for (int ${id}_i = 0; ${id}_i < ${maxSteps}; ${id}_i++) {\n`,
        `        vec3  ${id}_rp = ${id}_ro + ${id}_t * ${id}_rd;\n`,
        `        float ${id}_d  = ${sceneFn}(${id}_rp);\n`,
        `        if (${id}_d < 0.0005) { ${id}_hit = 1.0; ${id}_si = ${id}_i; break; }\n`,
        `        ${id}_t += ${id}_d;\n`,
        `        if (${id}_t > ${maxDist}) { ${id}_si = ${id}_i; break; }\n`,
        `    }\n`,
        `    float ${id}_iter = float(${id}_si) / float(${maxSteps});\n`,
        // Normal estimation
        `    vec3  ${id}_hp  = ${id}_ro + ${id}_t * ${id}_rd;\n`,
        `    float ${id}_e   = 0.001;\n`,
        `    vec3  ${id}_n   = normalize(vec3(\n`,
        `        ${sceneFn}(${id}_hp+vec3(${id}_e,0.0,0.0)) - ${sceneFn}(${id}_hp-vec3(${id}_e,0.0,0.0)),\n`,
        `        ${sceneFn}(${id}_hp+vec3(0.0,${id}_e,0.0)) - ${sceneFn}(${id}_hp-vec3(0.0,${id}_e,0.0)),\n`,
        `        ${sceneFn}(${id}_hp+vec3(0.0,0.0,${id}_e)) - ${sceneFn}(${id}_hp-vec3(0.0,0.0,${id}_e))\n`,
        `    ));\n`,
        // Lighting
        `    vec3  ${id}_ld  = normalize(vec3(${lx}, ${ly}, ${lz}));\n`,
        `    float ${id}_dif = clamp(dot(${id}_n, ${id}_ld), 0.0, 1.0);\n`,
        `    float ${id}_amb = 0.1 + 0.15 * (${id}_n.y * 0.5 + 0.5);\n`,
        `    vec3  ${id}_alb = vec3(${ar}, ${ag}, ${ab});\n`,
        `    vec3  ${id}_lit = ${id}_alb * (${id}_dif + ${id}_amb);\n`,
        // Fog / background blend
        `    float ${id}_fog = clamp(${id}_t / ${maxDist}, 0.0, 1.0);\n`,
        `    vec3  ${id}_bg  = vec3(${bgr}, ${bgg}, ${bgb});\n`,
        `    vec3  ${id}_color = mix(mix(${id}_lit, ${id}_bg, ${id}_fog), ${id}_bg, 1.0 - ${id}_hit);\n`,
        `    float ${id}_depth = ${id}_hit > 0.5 ? ${id}_t / ${maxDist} : 1.0;\n`,
        `    vec3  ${id}_normal = ${id}_n * ${id}_hit;\n`,
      ].join(''),
      outputVars: {
        color:  `${id}_color`,
        depth:  `${id}_depth`,
        normal: `${id}_normal`,
        iter:   `${id}_iter`,
      },
    };
  },
};

// Suppress unused import
void (RAY_RENDER_GLSL as unknown);
