/**
 * The Convert examples are the converter's own output for the Convert page's
 * Soft circle, stored so the example chunk doesn't carry the GLSL parser.
 * This converts the shader again and fails if the stored graphs have drifted.
 * To refresh them after a converter change:
 *
 *   UPDATE_CONVERT_EXAMPLES=1 npx vitest run convertExamples
 */
import { describe, expect, it } from 'vitest';
import { glslToGraph } from '../../glslToGraph';
import { optimizeGraph } from '../../optimize/optimizeGraph';
import { CONVERT_EXAMPLES } from '../../glslToGraph/examples';
import { estimateNodeHeight, layoutByRank } from '../graphLayout';
import type { GraphNode } from '../../types/nodeGraph';
import { SOFT_CIRCLE_AS_WRITTEN, SOFT_CIRCLE_OPTIMISED } from '../convertExampleNodes';

const plain = <T,>(v: T): T => JSON.parse(JSON.stringify(v)) as T;

describe('Convert examples', () => {
  const raw = glslToGraph(CONVERT_EXAMPLES.circle.code);
  const folded = optimizeGraph(raw.nodes, { minChain: 3, keepSliders: true }).nodes;
  // As the page does: a folded block sits where its last member was, so the columns are spaced again.
  const at = layoutByRank(folded, { heightOf: estimateNodeHeight, order: (a, b) => a.position.y - b.position.y });
  const opt = { nodes: folded.map((n): GraphNode => { const p = at.get(n.id); return p ? { ...n, position: p } : n; }) };

  it('are what the Convert page makes of the Soft circle, as written and optimised', async () => {
    if ((import.meta.env as Record<string, unknown>).UPDATE_CONVERT_EXAMPLES) {
      // Node's fs, named at run time: the app's types don't include Node.
      const fs = (await import(/* @vite-ignore */ `node:${'fs'}`)) as { writeFileSync: (f: URL, s: string) => void };
      fs.writeFileSync(new URL('../convertExampleNodes.ts', import.meta.url), `// Generated by src/store/__tests__/convertExamples.test.ts from the Convert page's Soft circle
// (glslToGraph, then optimizeGraph as the page runs it). Don't edit by hand:
//   UPDATE_CONVERT_EXAMPLES=1 npx vitest run convertExamples
import type { GraphNode } from '../types/nodeGraph';

export const SOFT_CIRCLE_AS_WRITTEN: GraphNode[] = ${JSON.stringify(plain(raw.nodes), null, 2)};

export const SOFT_CIRCLE_OPTIMISED: GraphNode[] = ${JSON.stringify(plain(opt.nodes), null, 2)};
`);
      return;
    }
    expect(raw.report.unsupported).toEqual([]);
    expect(SOFT_CIRCLE_AS_WRITTEN, 'the converter changed: refresh the stored graph (see the top of this file)').toEqual(plain(raw.nodes));
    expect(SOFT_CIRCLE_OPTIMISED, 'the optimiser changed: refresh the stored graph (see the top of this file)').toEqual(plain(opt.nodes));
    expect(SOFT_CIRCLE_OPTIMISED.length).toBeLessThan(SOFT_CIRCLE_AS_WRITTEN.length);
  });
});
