/**
 * moves.ts — the Expression Builder's move catalogue (docs/expression-builder-plan.md §1–2, phase 1).
 *
 * A *move* is a typed template with holes that transforms one variable `x`:
 *
 *   x * #a                       scale (zoom on space)        vec2 → vec2
 *   fract(x * #a) - #b           repeat                       vec2 → vec2
 *   x + #a * sin(x.yx * #b + $a) warp                         vec2 → vec2
 *   length(x) - $a               distance                     vec3 → float
 *
 * `#name` holes are numbers (sliders: default and range from the values seen), `$name` holes are
 * other variables (a time, a radius, a colour…), typed. Templates are glslPatterns syntax, so
 * `parseExpr` reads them and `compilePattern` matches them.
 *
 * Moves are mined from written code (mine.ts: Expression Blocks, Custom Functions and their helper
 * functions, imported and saved shaders) through the Code explorer's corpus (DocInput), with the
 * graph around each piece of code for context (context.ts). A few families are generated by type
 * instead (generated.ts: swizzles, one component driving another, products, rotations).
 *
 * Pure: docs in, a JSON-able catalogue out. The bundled examples' catalogue is built ahead
 * (prebuilt/moves.json, see exampleMoves.ts); the user's own code is mined on device (localMoves.ts).
 */
import { formatNumber, inferTypes, parseExpr, printExpr, allNodes, type Expr, type GlslType, type Role, type TypeEnv } from '../lib/glslPatterns';
import { compilePattern, matchNormalized, type N } from '../lib/glslPatterns/match';
import type { DocInput, Origin } from '../codeExplorer/types';
import type { GraphNode } from '../types/nodeGraph';
import { mineDoc } from './mine';
import { generatedMoves } from './generated';
import { moveId, varDefault, holeRange } from './shared';

export { moveId, varDefault, holeRange };

/** Bumped when the stored shape or the mining rules change: the prebuilt catalogue is rebuilt. */
export const MOVES_SCHEMA = 1;

// ── Context ───────────────────────────────────────────────────────────────────

/**
 * Where a move was used:
 *  - '2d': picture space (UV, fragCoord, and values computed in a 2D graph);
 *  - '3d-world': world space, inside a Scene Group or March Loop (or a shader's map/sdf function);
 *  - '3d-surface': on a surface, after the march (hit position, normal, shading);
 *  - '1d-time': a float driven by time only.
 */
export type Dimension = '2d' | '3d-world' | '3d-surface' | '1d-time';
export const DIMENSIONS: readonly Dimension[] = ['2d', '3d-world', '3d-surface', '1d-time'];

/** What fed the variable the move acted on. */
export type Feed =
  | 'uv' | 'fragCoord' | 'position' | 'hitPos' | 'normal' | 'rayDir' | 'rayOrigin'
  | 'time' | 'mouse' | 'distance' | 'colour' | 'cell' | 'loopIndex' | 'mask' | 'agent' | 'value' | 'constant' | 'unknown';

/** What the result went into: a role, or a palette / the output / a texture lookup. */
export type Into = Role | 'palette' | 'output' | 'sample';

export interface MoveContext {
  dim: Dimension;
  feed: Feed;
  into: Into;
  /** Pattern-index techniques (src/patterns) around the code's node, in this context (up to 8). */
  techniques: string[];
  /** Times seen in this context. */
  n: number;
}

// ── Moves ─────────────────────────────────────────────────────────────────────

export type MoveFamily =
  | 'scale' | 'offset' | 'repeat' | 'fold' | 'warp' | 'wave' | 'polar' | 'rotate' | 'distance' | 'colour'
  | 'cell' | 'mask' | 'blend' | 'clamp' | 'curve' | 'project' | 'normalize' | 'angle' | 'noise' | 'sample'
  | 'swizzle' | 'couple' | 'product' | 'build' | 'other';

export interface MoveSignature {
  /** The type of `x`. */
  in: GlslType;
  out: GlslType;
  /** What `x` stands for (space, colour, distance, time…); 'unknown' on generated moves means any. */
  role: Role;
  /** What the result stands for. */
  outRole: Role;
}

export interface NumberHole {
  name: string;
  kind: 'number';
  type: 'float' | 'int';
  /** The most used value. */
  default: number;
  /** A slider range covering the values seen. */
  range: { min: number; max: number };
  /** Smallest and largest value seen. */
  seenMin: number;
  seenMax: number;
  /** The most used values, with how often: [value, count]. */
  vals: Array<[number, number]>;
}

export interface VarHole {
  name: string;
  kind: 'var';
  type: GlslType;
  role: Role;
  /** Names it had in the code, most used first (up to 4). */
  names: string[];
  /** What `applyMove` puts there when nothing is given. */
  default: string;
}

export type MoveHole = NumberHole | VarHole;

/** A place a move was seen. `doc` indexes `Catalogue.docs`; `path` is the node's group path, its own id last. */
export interface MoveSource { doc: number; path?: string[]; field?: string; line?: number }

export interface CatalogueDoc {
  /** The Code explorer's doc id: `example:<key>`, `example-convert:<key>`, `saved:<name>`, `file:…`. */
  id: string;
  label: string;
  origin: Origin;
}

export interface Move {
  /** Stable: a hash of `key`. */
  id: string;
  /** Identity: input type, role and the template's shape with anonymous holes. */
  key: string;
  /** GLSL with `x` and holes. */
  template: string;
  family: MoveFamily;
  /** A glslPatterns idiom the template is (`domainWarp`, `cosinePalette`…), when it is one. */
  idiom?: string;
  sig: MoveSignature;
  holes: MoveHole[];
  /** Times seen. */
  count: number;
  /** Where (up to SOURCE_CAP places, different docs first); `sourceCount` is the full number. */
  sources: MoveSource[];
  sourceCount: number;
  contexts: MoveContext[];
  /** One step of a chain (an operation applied to `x`), as opposed to a compound of several. */
  step?: true;
  /** A compound's steps, innermost first (move ids). */
  steps?: string[];
  /** Made by type, not mined (generated.ts). */
  generated?: true;
}

/** Which move follows which along the same variable's chain (`from`'s result is `to`'s x). */
export interface OrderStat { from: string; to: string; dim: Dimension; n: number }

export interface Catalogue {
  schema: number;
  docs: CatalogueDoc[];
  moves: Move[];
  order: OrderStat[];
}

/** A doc to mine: the Code explorer's written code, and the graph it sits in (for context) when it is one. */
export interface MoveDoc {
  doc: DocInput;
  nodes?: readonly GraphNode[];
}

const SOURCE_CAP = 8;
const VALS_CAP = 8;
/** Techniques kept per context (the union of those seen). */
const TECH_CAP = 8;

// ── Building ──────────────────────────────────────────────────────────────────

/** One sighting of a move, as the miner reports it. */
export interface Instance {
  key: string;
  template: string;
  family: MoveFamily;
  idiom?: string;
  sig: MoveSignature;
  step: boolean;
  /** Keys of the steps of this compound (innermost first). */
  steps: string[];
  holes: Array<{ name: string; kind: 'number' | 'var'; type: GlslType; role?: Role; value?: number; varName?: string }>;
  /** The instance's own normalised tree (subject `__s`), for binding an existing template's holes. */
  norm: N;
  src: MoveSource;
  ctx: Omit<MoveContext, 'n'>;
}

interface Acc {
  move: Move;
  vals: Map<string, Map<number, number>>;
  names: Map<string, Map<string, number>>;
  ctx: Map<string, MoveContext>;
  srcDocs: Set<number>;
  stepKeys?: string[];
}

/** The template with its subject as `__s`, compiled for matching instances. */
const patternCache = new Map<string, N | null>();
function patternOf(template: string): N | null {
  if (patternCache.has(template)) return patternCache.get(template)!;
  let out: N | null = null;
  const r = parseExpr(template);
  if (r.ok) {
    const subst = new Map<number, string>();
    for (const n of allNodes(r.expr)) if (n.kind === 'ident' && n.name === 'x') subst.set(n.id, '__s');
    try { out = compilePattern(printExpr(r.expr, subst)); } catch { out = null; }
  }
  patternCache.set(template, out);
  return out;
}

/** Values are kept to 6 significant digits (the catalogue is data, not code). */
export const round6 = (v: number) => (Number.isFinite(v) ? Number(v.toPrecision(6)) : 0);

const bump = <K>(m: Map<K, number>, k: K, d = 1) => m.set(k, (m.get(k) ?? 0) + d);

export class CatalogueBuilder {
  private docs: CatalogueDoc[] = [];
  private docIndex = new Map<string, number>();
  private accs = new Map<string, Acc>();
  private order = new Map<string, number>();

  doc(d: CatalogueDoc): number {
    let i = this.docIndex.get(d.id);
    if (i === undefined) { i = this.docs.length; this.docs.push(d); this.docIndex.set(d.id, i); }
    return i;
  }

  private ensure(key: string, make: () => Move): Acc {
    let a = this.accs.get(key);
    if (!a) {
      const move = make();
      a = { move, vals: new Map(), names: new Map(), ctx: new Map(), srcDocs: new Set() };
      for (const h of move.holes) { if (h.kind === 'number') a.vals.set(h.name, new Map()); else a.names.set(h.name, new Map()); }
      this.accs.set(key, a);
    }
    return a;
  }

  private addContext(a: Acc, c: Omit<MoveContext, 'n'>, n: number) {
    const k = `${c.dim}|${c.feed}|${c.into}`;
    const have = a.ctx.get(k);
    if (have) {
      have.n += n;
      for (const t of c.techniques) if (!have.techniques.includes(t) && have.techniques.length < TECH_CAP) have.techniques.push(t);
    } else a.ctx.set(k, { ...c, techniques: c.techniques.slice(0, TECH_CAP), n });
  }

  private addSource(a: Acc, s: MoveSource, docId: number) {
    a.move.sourceCount++;
    if (a.move.sources.length < SOURCE_CAP && !a.srcDocs.has(docId)) { a.move.sources.push(s); a.srcDocs.add(docId); }
  }

  addInstance(inst: Instance): void {
    const a = this.ensure(inst.key, () => ({
      id: moveId(inst.key), key: inst.key, template: inst.template, family: inst.family, ...(inst.idiom ? { idiom: inst.idiom } : {}), sig: inst.sig,
      holes: inst.holes.map(h => (h.kind === 'number'
        ? { name: h.name, kind: 'number', type: h.type === 'int' ? 'int' : 'float', default: 0, range: { min: 0, max: 1 }, seenMin: Infinity, seenMax: -Infinity, vals: [] }
        : { name: h.name, kind: 'var', type: h.type, role: h.role ?? 'value', names: [], default: varDefault(h.type, h.role ?? 'value') }) as MoveHole),
      count: 0, sources: [], sourceCount: 0, contexts: [],
    }));
    const m = a.move;
    m.count++;
    if (inst.step) m.step = true;
    if (inst.steps.length && !a.stepKeys) a.stepKeys = inst.steps;
    this.addSource(a, inst.src, inst.src.doc);
    this.addContext(a, inst.ctx, 1);
    // Bind this sighting's numbers and names to the move's own holes.
    let bound: Array<{ name: string; value?: number; varName?: string }> | null = null;
    if (m.template === inst.template) bound = inst.holes;
    else {
      const p = patternOf(m.template);
      const b = p ? matchNormalized(p, inst.norm) : null;
      if (b) bound = Object.entries(b).map(([k, v]) => ({ name: m.holes.find(h => h.name.slice(1) === k)?.name ?? k, value: v.value, varName: v.expr.kind === 'ident' ? v.expr.name : undefined }));
    }
    for (const h of bound ?? []) {
      if (h.value !== undefined && a.vals.has(h.name)) bump(a.vals.get(h.name)!, round6(h.value));
      if (h.varName && a.names.has(h.name)) bump(a.names.get(h.name)!, h.varName);
    }
  }

  addPair(fromKey: string, toKey: string, dim: Dimension, n = 1): void {
    bump(this.order, `${moveId(fromKey)}>${moveId(toKey)}>${dim}`, n);
  }

  /** Add a whole catalogue (another doc set, the prebuilt one, a local one). */
  addCatalogue(cat: Catalogue): void {
    const docMap = cat.docs.map(d => this.doc(d));
    const idToKey = new Map(cat.moves.map(m => [m.id, m.key]));
    for (const src of cat.moves) {
      // Generated moves are added once, at the end (addGenerated), never merged into mined ones.
      if (src.generated) continue;
      const a = this.ensure(src.key, () => ({ ...src, holes: src.holes.map(h => ({ ...h, ...(h.kind === 'number' ? { vals: [] } : { names: [] }) }) as MoveHole), count: 0, sources: [], sourceCount: 0, contexts: [], steps: undefined }));
      const m = a.move;
      m.count += src.count;
      if (src.step) m.step = true;
      if (src.steps && !a.stepKeys) a.stepKeys = src.steps.map(id => idToKey.get(id)).filter((k): k is string => !!k);
      for (const s of src.sources) {
        const d = docMap[s.doc];
        if (m.sources.length < SOURCE_CAP && !a.srcDocs.has(d)) { m.sources.push({ ...s, doc: d }); a.srcDocs.add(d); }
      }
      m.sourceCount += src.sourceCount;
      for (const c of src.contexts) this.addContext(a, c, c.n);
      for (const h of src.holes) {
        if (h.kind === 'number') {
          const vm = a.vals.get(h.name);
          if (!vm) continue;
          for (const [v, n] of h.vals) bump(vm, v, n);
          // Values beyond the kept few still widen the range.
          if (Number.isFinite(h.seenMin)) { bump(vm, h.seenMin, 0); bump(vm, h.seenMax, 0); }
        } else {
          const nm = a.names.get(h.name);
          if (nm) h.names.forEach((x, i) => bump(nm, x, h.names.length - i));
        }
      }
    }
    for (const o of cat.order) {
      const from = idToKey.get(o.from), to = idToKey.get(o.to);
      if (from && to) bump(this.order, `${moveId(from)}>${moveId(to)}>${o.dim}`, o.n);
    }
  }

  /** Add generated moves (skipped where a mined move has the same identity). */
  addGenerated(moves: readonly Move[]): void {
    for (const g of moves) if (!this.accs.has(g.key)) this.ensure(g.key, () => ({ ...g, holes: g.holes.map(h => ({ ...h })), contexts: [] })).ctx = new Map(g.contexts.map(c => [`${c.dim}|${c.feed}|${c.into}`, { ...c }]));
  }

  finish(): Catalogue {
    const moves: Move[] = [];
    for (const a of this.accs.values()) {
      const m = a.move;
      m.holes = m.holes.map(h => {
        if (h.kind === 'number') {
          const vm = a.vals.get(h.name);
          if (!vm || !vm.size) return h;
          const entries = [...vm.entries()];
          const counted = entries.filter(([, n]) => n > 0).sort((x, y) => y[1] - x[1] || x[0] - y[0]);
          const all = entries.map(([v]) => v);
          const seenMin = Math.min(...all), seenMax = Math.max(...all);
          const def = counted[0]?.[0] ?? h.default;
          return { ...h, default: def, seenMin, seenMax, range: holeRange(seenMin, seenMax, def), vals: counted.slice(0, VALS_CAP) };
        }
        const nm = a.names.get(h.name);
        const names = nm ? [...nm.entries()].sort((x, y) => y[1] - x[1] || x[0].localeCompare(y[0])).slice(0, 4).map(([k]) => k) : h.names;
        return { ...h, names };
      });
      m.contexts = [...a.ctx.values()].map(c => ({ ...c, techniques: [...c.techniques].sort() })).sort((x, y) => y.n - x.n || x.dim.localeCompare(y.dim) || x.feed.localeCompare(y.feed) || x.into.localeCompare(y.into));
      if (a.stepKeys && a.stepKeys.length && !(a.stepKeys.length === 1 && a.stepKeys[0] === m.key)) {
        const ids = a.stepKeys.filter(k => this.accs.has(k)).map(moveId);
        if (ids.length) m.steps = ids; else delete m.steps;
      } else delete m.steps;
      moves.push(m);
    }
    moves.sort((x, y) => Number(!!x.generated) - Number(!!y.generated) || y.count - x.count || x.key.localeCompare(y.key));
    const ids = new Set(moves.map(m => m.id));
    const order: OrderStat[] = [];
    for (const [k, n] of this.order) {
      const [from, to, dim] = k.split('>');
      if (ids.has(from) && ids.has(to)) order.push({ from, to, dim: dim as Dimension, n });
    }
    order.sort((x, y) => y.n - x.n || x.from.localeCompare(y.from) || x.to.localeCompare(y.to) || x.dim.localeCompare(y.dim));
    return { schema: MOVES_SCHEMA, docs: this.docs, moves, order };
  }
}

// ── API ───────────────────────────────────────────────────────────────────────

/** Mine docs into a catalogue (with the generated moves unless `generated: false`). */
export function buildCatalogue(docs: readonly MoveDoc[], opts: { generated?: boolean } = {}): Catalogue {
  const b = new CatalogueBuilder();
  for (const d of docs) mineDoc(d, b);
  if (opts.generated !== false) b.addGenerated(generatedMoves());
  return b.finish();
}

/** Several catalogues as one (the prebuilt examples plus the user's own, say). */
export function mergeCatalogues(...cats: readonly Catalogue[]): Catalogue {
  const b = new CatalogueBuilder();
  for (const c of cats) b.addCatalogue(c);
  b.addGenerated(generatedMoves());
  return b.finish();
}

let active: Catalogue | null = null;
/** The catalogue `movesFor` reads when none is passed (localMoves.ts sets it). */
export function setActiveCatalogue(cat: Catalogue | null): void { active = cat; }
export function activeCatalogue(): Catalogue {
  if (!active) { const b = new CatalogueBuilder(); b.addGenerated(generatedMoves()); active = b.finish(); }
  return active;
}

export interface Seed {
  type: GlslType;
  role?: Role;
  dimension: Dimension;
  /** What fed it, what it goes into, the techniques around it: narrow to moves seen with any of them. */
  feeds?: Feed | Feed[];
  into?: Into | Into[];
  techniques?: string[];
}

const asList = <T>(v: T | T[] | undefined): T[] | undefined => (v === undefined ? undefined : Array.isArray(v) ? v : [v]);

/**
 * The moves that apply to a seed: same input type, the seed's role (or any, for generated moves),
 * seen in the seed's dimension; narrowed by feeds / into / techniques when given. Unranked (most
 * seen first); phase 3 ranks.
 */
export function movesFor(seed: Seed, cat: Catalogue = activeCatalogue()): Move[] {
  const feeds = asList(seed.feeds), into = asList(seed.into), techs = seed.techniques;
  return cat.moves.filter(m => {
    if (m.sig.in !== seed.type) return false;
    if (seed.role && m.sig.role !== seed.role && m.sig.role !== 'unknown') return false;
    const cs = m.contexts.filter(c => c.dim === seed.dimension);
    if (!cs.length) return false;
    if (m.generated) return true;
    if (feeds && !cs.some(c => feeds.includes(c.feed))) return false;
    if (into && !cs.some(c => into.includes(c.into))) return false;
    if (techs?.length && !cs.some(c => c.techniques.some(t => techs.includes(t)))) return false;
    return true;
  });
}

/** Moves that followed `move` along a chain (in a dimension, or all), most often first. */
export function followers(move: Move | string, cat: Catalogue = activeCatalogue(), dim?: Dimension): Array<{ move: Move; n: number }> {
  const byId = new Map(cat.moves.map(m => [m.id, m]));
  const m = typeof move === 'string' ? byId.get(move) : move;
  if (!m) return [];
  // A compound is followed by what follows its last step.
  const from = new Set([m.id, ...(m.steps?.length ? [m.steps[m.steps.length - 1]] : [])]);
  const tally = new Map<string, number>();
  for (const o of cat.order) if (from.has(o.from) && (!dim || o.dim === dim)) bump(tally, o.to, o.n);
  return [...tally.entries()].map(([id, n]) => ({ move: byId.get(id)!, n })).filter(x => x.move).sort((a, b) => b.n - a.n);
}

/** The holes' environment for type-checking a template. */
export function templateEnv(move: Pick<Move, 'holes' | 'sig'>): TypeEnv {
  const env: TypeEnv = { x: move.sig.in };
  for (const h of move.holes) env[h.name] = h.type;
  return env;
}

/**
 * The move applied to an expression: `x` becomes `expr` (parenthesised where needed), number holes
 * their values (or defaults), variable holes the given code (or their defaults).
 */
export function applyMove(expr: string, move: Pick<Move, 'template' | 'holes'>, holes: Record<string, number | string> = {}): string {
  const t = parseExpr(move.template);
  if (!t.ok) throw new Error(`Move template “${move.template}” doesn't parse: ${t.error}`);
  const e = parseExpr(expr);
  if (!e.ok) throw new Error(`“${expr}” doesn't parse: ${e.error}`);
  const byName = new Map(move.holes.map(h => [h.name, h]));
  const num = (v: number, int: boolean, at: Expr): Expr => {
    const lit: Expr = { kind: 'num', value: Math.abs(v), raw: formatNumber(Math.abs(v), int), int, id: at.id, start: at.start, end: at.end };
    return v < 0 ? { kind: 'unary', op: '-', arg: lit, id: at.id, start: at.start, end: at.end } : lit;
  };
  const code = (text: string): Expr | null => { const r = parseExpr(text); return r.ok ? r.expr : null; };
  // Graft: the seed's tree for x, numbers and code for holes; printing then adds only the parentheses precedence needs.
  const graft = (n: Expr): Expr => {
    switch (n.kind) {
      case 'ident': {
        if (n.name === 'x') return e.expr;
        const h = byName.get(n.name);
        if (!h) return n;
        const given = holes[n.name] ?? holes[n.name.slice(1)];
        if (h.kind === 'number') {
          const v = typeof given === 'number' ? given : typeof given === 'string' && given.trim() !== '' && Number.isFinite(Number(given)) ? Number(given) : h.default;
          return num(v, h.type === 'int', n);
        }
        if (typeof given === 'number') return num(given, false, n);
        return (typeof given === 'string' && given.trim() ? code(given) : null) ?? code(h.default) ?? n;
      }
      case 'call': return { ...n, args: n.args.map(graft) };
      case 'binary': return { ...n, left: graft(n.left), right: graft(n.right) };
      case 'unary': return { ...n, arg: graft(n.arg) };
      case 'member': return { ...n, object: graft(n.object) };
      case 'index': return { ...n, object: graft(n.object), index: graft(n.index) };
      case 'ternary': return { ...n, test: graft(n.test), then: graft(n.then), else: graft(n.else) };
      default: return n;
    }
  };
  return printExpr(graft(t.expr));
}

/** The type of `text` with the given names in scope ('unknown' when it doesn't parse or type). */
export function typeOfExpr(text: string, env: TypeEnv = {}): GlslType {
  const r = parseExpr(text);
  if (!r.ok) return 'unknown';
  return inferTypes(r.expr, env).get(r.expr.id) ?? 'unknown';
}

/** Readable name: the family, said for the role ("zoom" for scale on space, "brightness" on colour). */
export function moveLabel(m: Pick<Move, 'family' | 'sig'>): string {
  const r = m.sig.role;
  if (m.family === 'scale') return r === 'space' ? 'zoom' : r === 'colour' ? 'brightness' : r === 'time' ? 'speed' : 'scale';
  if (m.family === 'offset') return r === 'space' ? 'move' : r === 'colour' ? 'tint' : r === 'time' ? 'delay' : 'offset';
  if (m.family === 'colour' && r === 'space') return 'colour by space';
  return m.family;
}

/** "Fractal Rings", or "your import: Shadertoy tunnel" for the user's own code. */
export function sourceLabel(cat: Pick<Catalogue, 'docs'>, s: MoveSource): string {
  const d = cat.docs[s.doc];
  if (!d) return '?';
  if (d.origin === 'example') return d.label;
  if (d.id.startsWith('file:') || d.id.startsWith('shader:') || d.id.startsWith('convert:')) return `your import: ${d.label}`;
  return `your graph: ${d.label}`;
}

export type { Expr };
